import { Preparation } from './types';

export const preparations: Preparation[] = [
  // ─── IV PREPARATIONS (20) ────────────────────────────────────────────────
  {
    id: 'iv-01',
    name: 'High-Dose Vitamin C IV',
    route: 'IV',
    activeIngredients: [{ name: 'Ascorbic Acid', concentration: '25–75 g in 250 mL NS' }],
    ebmLevel: 'A',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Cancer support', 'Immune dysfunction', 'Viral infections', 'Oxidative stress', 'Sepsis adjunct', 'Chronic fatigue'],
    contraindications: ['G6PD deficiency', 'Oxalate nephropathy history', 'eGFR < 30', 'Hemochromatosis'],
    interactions: [
      { drug: 'Warfarin', severity: 'moderate', description: 'High-dose Vit C may enhance anticoagulant effect; monitor INR closely.' },
      { drug: 'Metformin', severity: 'minor', description: 'May modestly improve insulin sensitivity; watch for hypoglycemia.' },
      { drug: 'Deferoxamine', severity: 'major', description: 'Concurrent use increases iron toxicity risk; avoid combination.' },
      { drug: 'Statins', severity: 'minor', description: 'Antioxidant co-administration may theoretically reduce statin efficacy in some contexts.' },
    ],
    sideEffects: ['Oxaluria (high doses)', 'Kidney stone risk', 'Osmotic diarrhea (IV rate-related)', 'Vein irritation'],
    evidenceSources: ['Padayatty SJ et al., Ann Intern Med 2004; PMID 14757619', 'Fowler AA et al., JAMA 2019; PMID 31573637', 'Carr AC, Nutrients 2020'],
    benefits: 'Potent antioxidant that neutralises reactive oxygen species, enhances neutrophil function, supports collagen synthesis, and at pharmacologic IV doses achieves pro-oxidant cytotoxicity in tumour micro-environments. Strong evidence for improved outcomes in sepsis and cancer adjunctive care.',
    organSafety: {
      renal: 'Contraindicated in eGFR < 30; may cause oxalate nephropathy with prolonged high-dose use. Screen eGFR and urine oxalate before initiating.',
      hepatic: 'Generally safe; hepatic metabolism is minimal. No dose adjustment required for mild-moderate hepatic impairment.',
    },
    adminNotes: 'Check G6PD status before first dose. Infuse over 60–90 min. Monitor urine oxalate after 4 sessions.',
  },
  {
    id: 'iv-02',
    name: 'Glutathione IV',
    route: 'IV',
    activeIngredients: [{ name: 'Reduced L-Glutathione (GSH)', concentration: '600–2400 mg in 100 mL NS' }],
    ebmLevel: 'C',
    ebmCategory: 'Integrative/Empirical',
    indications: ['Liver detoxification', 'Peripheral neuropathy', 'Oxidative stress', 'Parkinson\'s adjunct', 'Post-chemotherapy recovery', 'Heavy metal detox'],
    contraindications: ['Active asthma (may trigger bronchospasm IV)', 'Hypersensitivity to sulphur compounds'],
    interactions: [
      { drug: 'Cisplatin', severity: 'major', description: 'May reduce chemotherapy efficacy; oncology consult required before concurrent use.' },
      { drug: 'Nitroglycerin', severity: 'moderate', description: 'Glutathione may potentiate vasodilation; monitor BP.' },
    ],
    sideEffects: ['Bronchospasm (rare, IV bolus)', 'Injection-site discomfort', 'Transient skin lightening with repeated use', 'Zinc depletion with chronic use'],
    evidenceSources: ['Witschi A et al., Eur J Clin Pharmacol 1992; PMID 1516452', 'Perricone C et al., Clin Exp Immunol 2009', 'German Complementary Medicine Monograph 2021'],
    benefits: 'Master endogenous antioxidant. IV delivery bypasses poor oral bioavailability, directly replenishing intracellular GSH stores. Supports hepatic phase-II detoxification, reduces cisplatin-induced neuropathy, and shows emerging evidence in Parkinson\'s motor symptoms.',
    organSafety: {
      renal: 'Safe at standard doses. IV administration avoids first-pass degradation. No renal dose adjustment needed unless eGFR < 15.',
      hepatic: 'Specifically beneficial in hepatic conditions. Supports Phase II glutathione-S-transferase activity. Preferred in NAFLD and drug-induced liver injury.',
    },
  },
  {
    id: 'iv-03',
    name: 'Alpha-Lipoic Acid IV',
    route: 'IV',
    activeIngredients: [{ name: 'R-Alpha-Lipoic Acid', concentration: '600–1200 mg in 250 mL NS' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Diabetic peripheral neuropathy', 'Oxidative stress', 'Hepatic steatosis', 'Metabolic syndrome', 'Chronic fatigue'],
    contraindications: ['Thiamine deficiency (may precipitate Wernicke\'s)', 'eGFR < 15'],
    interactions: [
      { drug: 'Metformin', severity: 'moderate', description: 'Synergistic blood glucose lowering; monitor closely for hypoglycemia.' },
      { drug: 'Levothyroxine', severity: 'moderate', description: 'ALA may reduce T4 absorption when taken concurrently; separate dosing by 4 hours.' },
      { drug: 'Insulin', severity: 'moderate', description: 'Additive hypoglycemic effect; adjust insulin dose as needed.' },
    ],
    sideEffects: ['Nausea (rapid infusion)', 'Hypoglycemia', 'Thiamine depletion with long-term use', 'Skin rash (rare)'],
    evidenceSources: ['Ziegler D et al., Diabetes Care 2006; PMID 16873786', 'SYDNEY 2 Trial, Diabetes Care 2006', 'German Diabetes Society Guidelines 2023'],
    benefits: 'Dual aqueous and lipid-phase antioxidant. IV form achieves plasma concentrations 20–50× greater than oral. Level B RCT evidence supports significant NRS (neuropathy) score improvement in diabetic peripheral neuropathy after 3-week IV course. Also regenerates endogenous antioxidants (Vit C, E, glutathione).',
    organSafety: {
      renal: 'Renally cleared; use caution with eGFR 15–30. Monitor for accumulation with severe CKD.',
      hepatic: 'Hepatoprotective at therapeutic doses. Studied in NAFLD with favourable hepatic enzyme profiles.',
    },
    adminNotes: 'Ensure thiamine sufficiency before initiation. Infuse over 30 min. Protect from light.',
  },
  {
    id: 'iv-04',
    name: 'Magnesium Sulfate IV',
    route: 'IV',
    activeIngredients: [{ name: 'Magnesium Sulfate', concentration: '1–4 g in 100 mL NS' }],
    ebmLevel: 'A',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Hypomagnesemia', 'Migraine acute', 'Muscle cramps', 'Arrhythmia (Torsades)', 'Pre-eclampsia', 'Chronic fatigue', 'Fibromyalgia'],
    contraindications: ['Hypermagnesemia', 'Heart block (without pacemaker)', 'Myasthenia gravis', 'eGFR < 20'],
    interactions: [
      { drug: 'Calcium channel blockers', severity: 'moderate', description: 'Additive hypotensive and negative chronotropic effect; monitor BP and HR.' },
      { drug: 'Digoxin', severity: 'moderate', description: 'Hypomagnesemia worsens digoxin toxicity; correction is beneficial.' },
      { drug: 'Neuromuscular blocking agents', severity: 'major', description: 'Potentiates neuromuscular blockade; avoid concurrent use.' },
    ],
    sideEffects: ['Flushing', 'Hypotension (rapid infusion)', 'Respiratory depression (overdose)', 'Nausea'],
    evidenceSources: ['Mauskop A et al., Headache 2012; PMID 22486536', 'ESC Guidelines Arrhythmia 2022', 'Cochrane Review Magnesium Migraine 2021'],
    benefits: 'Essential cofactor in >300 enzymatic reactions. IV delivery achieves rapid correction of hypomagnesemia. Level A evidence for acute migraine reduction (especially with aura), tocolytic effect, and prevention of eclamptic seizures. Broad clinical utility in metabolic and neurological presentations.',
    organSafety: {
      renal: 'Renally excreted — dose-limit strictly in CKD. Contraindicated eGFR < 20. Check serum Mg 2–4 h post-infusion.',
      hepatic: 'No hepatic dose adjustment required. Safe in hepatic impairment.',
    },
  },
  {
    id: 'iv-05',
    name: 'B-Complex IV (B1/B2/B3/B5/B6/B12)',
    route: 'IV',
    activeIngredients: [
      { name: 'Thiamine (B1)', concentration: '100 mg' },
      { name: 'Pyridoxine (B6)', concentration: '50 mg' },
      { name: 'Hydroxocobalamin (B12)', concentration: '1000 mcg' },
    ],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Fatigue', 'Peripheral neuropathy', 'B-vitamin deficiency', 'Chronic alcohol use', 'Malabsorption syndromes', 'Cognitive decline'],
    contraindications: ['Hypersensitivity to cobalamin', 'Leber\'s hereditary optic neuropathy (B12 caution)'],
    interactions: [
      { drug: 'Metformin', severity: 'moderate', description: 'Metformin reduces B12 absorption; IV supplementation corrects deficiency.' },
      { drug: 'Levodopa', severity: 'moderate', description: 'B6 (pyridoxine) accelerates peripheral levodopa metabolism; monitor Parkinson\'s control.' },
    ],
    sideEffects: ['Anaphylaxis (B12, rare)', 'Rash', 'Urine discolouration (riboflavin, harmless)', 'Injection-site pain'],
    evidenceSources: ['Clarke R et al., NEJM 2010; PMID 20462328', 'Stover PJ, Nutr Rev 2004', 'EFSA Scientific Opinion Vitamins 2022'],
    benefits: 'Synergistic IV B-vitamin delivery bypasses GI malabsorption. Thiamine is essential for neurological function and energy metabolism; B6 supports neurotransmitter synthesis; B12 corrects macrocytic anaemia and neuropathy. Particularly valuable in patients with Metformin use, chronic fatigue, or malabsorption.',
    organSafety: {
      renal: 'Water-soluble; excess excreted renally. Safe across all eGFR ranges at standard doses.',
      hepatic: 'Safe. B-vitamins are processed hepatically but not hepatotoxic at therapeutic doses.',
    },
  },
  {
    id: 'iv-06',
    name: 'NAD+ IV (Nicotinamide Adenine Dinucleotide)',
    route: 'IV',
    activeIngredients: [{ name: 'NAD+', concentration: '250–1000 mg in 250 mL NS' }],
    ebmLevel: 'C',
    ebmCategory: 'Integrative/Empirical',
    indications: ['Chronic fatigue syndrome', 'Neurodegenerative support', 'Addiction recovery', 'Anti-aging', 'Long COVID fatigue', 'Mitochondrial dysfunction'],
    contraindications: ['Active malignancy (theoretical — proliferative concern)', 'Pregnancy'],
    interactions: [
      { drug: 'PARP inhibitors (Olaparib)', severity: 'major', description: 'NAD+ may reduce PARP inhibitor efficacy; oncology review required.' },
      { drug: 'Nicotinic acid', severity: 'minor', description: 'Additive flushing; avoid concurrent high-dose niacin.' },
    ],
    sideEffects: ['Flushing', 'Nausea', 'Chest tightness (rapid infusion)', 'Fatigue (die-off reaction first 24 h)'],
    evidenceSources: ['Rajman L et al., Cell Metab 2018; PMID 29514069', 'Yoshino J et al., Cell Metab 2021; PMID 34450027', 'Integrative Medicine Monograph 2023'],
    benefits: 'Central coenzyme in cellular energy metabolism (glycolysis, TCA cycle, oxidative phosphorylation). Declines with age. IV delivery achieves supraphysiologic plasma peaks rapidly. Emerging evidence for improved cellular energetics in CFS/ME and long COVID. Sirtuins and PARP activity dependent on NAD+.',
    organSafety: {
      renal: 'Generally safe. Water-soluble metabolites cleared renally. No dose adjustment needed in mild-moderate CKD.',
      hepatic: 'Hepatically processed via NMN and NR pathways. No hepatotoxicity reported at standard doses.',
    },
    adminNotes: 'Infuse slowly over 2–4 h. Reduce rate immediately if chest tightness. Start at 250 mg for first infusion.',
  },
  {
    id: 'iv-07',
    name: 'Phosphatidylcholine IV',
    route: 'IV',
    activeIngredients: [{ name: 'Phosphatidylcholine (PC)', concentration: '2.5 g in 250 mL' }],
    ebmLevel: 'C',
    ebmCategory: 'Integrative/Empirical',
    indications: ['Non-alcoholic fatty liver disease', 'Cognitive decline', 'Lipid metabolism disorders', 'Liver cell regeneration', 'Arteriosclerosis support'],
    contraindications: ['Soy or egg allergy (phospholipid source)', 'Acute hepatitis'],
    interactions: [
      { drug: 'Cholinesterase inhibitors (Donepezil)', severity: 'moderate', description: 'Additive cholinergic effect; monitor for bradycardia and GI symptoms.' },
      { drug: 'Warfarin', severity: 'minor', description: 'May modestly affect platelet aggregation; monitor INR.' },
    ],
    sideEffects: ['Nausea', 'Diarrhoea', 'Fishy body odour (TMAO conversion)', 'Flushing'],
    evidenceSources: ['Kuntz E, Hepatology 1994; PMID 8175435', 'Stremmel W, Eur J Clin Pharmacol 2005', 'German Pharmacopoeia / Hepatology Monograph 2020'],
    benefits: 'Essential phospholipid supporting hepatocyte membrane integrity, bile flow, and lipid emulsification. IV PC corrects phospholipid deficiency in hepatic disease. Choline moiety supports acetylcholine synthesis and cognitive function. Evidence in NAFLD for hepatic enzyme normalisation and improved liver histology.',
    organSafety: {
      renal: 'Minimal renal involvement. Safe across CKD stages except ESKD (fluid load caution).',
      hepatic: 'Specifically hepatoprotective; supports hepatocyte regeneration. Use cautiously in severe cholestatic disease.',
    },
  },
  {
    id: 'iv-08',
    name: "Myers' Cocktail IV",
    route: 'IV',
    activeIngredients: [
      { name: 'Magnesium chloride', concentration: '200 mg' },
      { name: 'Calcium gluconate', concentration: '200 mg' },
      { name: 'B-Complex + B12', concentration: '1 mL each' },
      { name: 'Ascorbic acid', concentration: '1000 mg' },
    ],
    ebmLevel: 'C',
    ebmCategory: 'Integrative/Empirical',
    indications: ['Fibromyalgia', 'Chronic fatigue', 'Migraine prophylaxis', 'General wellness', 'Immune support', 'Asthma adjunct'],
    contraindications: ['Hypermagnesemia', 'Hypercalcemia', 'eGFR < 30', 'G6PD deficiency (Vit C component)'],
    interactions: [
      { drug: 'Digoxin', severity: 'moderate', description: 'Calcium and magnesium affect digoxin cardiotoxicity; monitor ECG.' },
      { drug: 'Levodopa', severity: 'moderate', description: 'B6 component accelerates peripheral levodopa breakdown.' },
    ],
    sideEffects: ['Warmth/flushing', 'Hypotension', 'Nausea', 'Metallic taste', 'Palpitations (rapid infusion)'],
    evidenceSources: ['Gaby AR, Alt Med Rev 2002; PMID 11821490', 'Massey PB, Altern Ther Health Med 2007', 'Integrative Medicine Review 2021'],
    benefits: 'Multi-nutrient IV blend popularised by John Myers, MD. Provides synergistic electrolyte, vitamin and antioxidant repletion in a single infusion. Observational evidence and case series support improvement in fibromyalgia pain, migraine frequency, and chronic fatigue. Broad applicability in nutritional depletion states.',
    organSafety: {
      renal: 'Screen eGFR before use. Avoid in eGFR < 30 due to magnesium and calcium accumulation risk.',
      hepatic: 'No significant hepatic risk at standard doses. Safe in mild hepatic impairment.',
    },
    adminNotes: 'Infuse over 20–30 min IV slow push or piggyback. Have calcium gluconate available as antidote.',
  },
  {
    id: 'iv-09',
    name: 'Selenium IV (Sodium Selenite)',
    route: 'IV',
    activeIngredients: [{ name: 'Sodium Selenite', concentration: '500–2000 mcg in 100 mL NS' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Selenium deficiency', 'Thyroid autoimmune disease (Hashimoto\'s)', 'Sepsis adjunct', 'Critical illness', 'Immune support'],
    contraindications: ['Selenium toxicity (selenosis)', 'Confirmed selenium sufficiency without deficiency'],
    interactions: [
      { drug: 'Warfarin', severity: 'minor', description: 'Selenium may modestly affect clotting; monitor INR.' },
      { drug: 'Cisplatin', severity: 'moderate', description: 'High-dose selenium may reduce platinum-based chemotherapy toxicity; consider oncology co-management.' },
    ],
    sideEffects: ['Garlic-breath odour', 'Nausea', 'Selenosis (overdose: hair loss, nail changes)', 'Fatigue'],
    evidenceSources: ['Rayman MP, Lancet 2012; PMID 21507558', 'Duntas LH, Thyroid 2010; PMID 20883140', 'ESPEN Micronutrient Guidelines 2022'],
    benefits: 'Essential trace element and cofactor of glutathione peroxidase. IV delivery corrects critical deficiency rapidly. Level B evidence for mortality benefit in selenium-deficient ICU patients. Hashimoto\'s thyroiditis: reduces anti-TPO antibodies at 200 mcg/day. Selenoprotein P and thioredoxin reductase activity are selenium-dependent.',
    organSafety: {
      renal: 'Renally cleared. Reduce dose in eGFR < 30 to avoid selenosis. Monitor serum selenium levels.',
      hepatic: 'No hepatotoxicity at therapeutic doses. Selenium-containing enzymes protect hepatocytes from oxidative injury.',
    },
  },
  {
    id: 'iv-10',
    name: 'Vitamin D3 IV (Cholecalciferol)',
    route: 'IV',
    activeIngredients: [{ name: 'Cholecalciferol', concentration: '300,000–600,000 IU single dose IM/IV' }],
    ebmLevel: 'A',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Severe Vitamin D deficiency (25-OH-D3 < 12 ng/mL)', 'Malabsorption syndromes', 'Post-bariatric surgery', 'Osteoporosis with malabsorption', 'Immune modulation'],
    contraindications: ['Hypercalcemia', 'Hypercalciuria', 'Sarcoidosis', 'Granulomatous diseases', 'Vitamin D toxicity'],
    interactions: [
      { drug: 'Thiazide diuretics', severity: 'moderate', description: 'Additive hypercalcemia risk; monitor serum calcium.' },
      { drug: 'Digoxin', severity: 'moderate', description: 'Hypercalcemia from excessive Vit D potentiates digoxin toxicity.' },
      { drug: 'Statins', severity: 'minor', description: 'Some statins increase Vit D levels; monitor 25-OH-D3 post-initiation.' },
    ],
    sideEffects: ['Hypercalcemia (overdose)', 'Hypercalciuria', 'Nausea', 'Polyuria', 'Renal calculi'],
    evidenceSources: ['Holick MF, NEJM 2007; PMID 17634462', 'Endocrine Society Guidelines Vitamin D 2023', 'NICE Guideline NG187 2022'],
    benefits: 'Rapidly corrects severe deficiency via single high-dose parenteral administration, bypassing GI malabsorption. Vitamin D3 is converted to 25-OH-D3 in liver and 1,25-OH2-D3 (calcitriol) in kidney. Supports calcium-phosphate homeostasis, immune regulation, muscle function, and mood. Level A evidence for fracture prevention and immune modulation.',
    organSafety: {
      renal: 'Calcitriol produced in kidney — impaired in CKD. In renal patients use activated 1,25-OH2-D3 (calcitriol) directly. Monitor Ca/P product.',
      hepatic: 'Hepatic 25-hydroxylation required. Severe hepatic failure may impair conversion; use calcitriol directly.',
    },
  },
  {
    id: 'iv-11',
    name: 'L-Carnitine IV',
    route: 'IV',
    activeIngredients: [{ name: 'L-Carnitine', concentration: '1–3 g in 100 mL NS' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Carnitine deficiency', 'Haemodialysis-associated carnitine depletion', 'Peripheral arterial disease', 'Cardiac support', 'Fatigue in CKD', 'Statin-induced myopathy'],
    contraindications: ['Seizure disorder history (large IV doses)', 'Trimethylaminuria'],
    interactions: [
      { drug: 'Warfarin', severity: 'moderate', description: 'L-carnitine may potentiate anticoagulant effect; monitor INR.' },
      { drug: 'Thyroid hormone (Levothyroxine)', severity: 'moderate', description: 'Carnitine may antagonise thyroid hormone at peripheral receptor level; monitor TFTs.' },
    ],
    sideEffects: ['Fishy body odour (TMAO)', 'Nausea', 'Diarrhoea', 'Seizure risk (high IV dose)', 'Hypoglycemia in fasting'],
    evidenceSources: ['Loster H, Clin Investig 1994; PMID 7859297', 'Signorelli SS, Vasc Med 2006; PMID 16669411', 'KDOQI CKD Nutrition Guidelines 2020'],
    benefits: 'Transports long-chain fatty acids across the inner mitochondrial membrane for beta-oxidation. IV form achieves rapid tissue repletion in deficiency states. Haemodialysis patients are systematically carnitine-depleted. Level B RCT evidence for improvement in intermittent claudication (walking distance) and dialysis-associated carnitine depletion.',
    organSafety: {
      renal: 'Renally cleared; haemodialysis removes ~70% per session — supplementation is standard in dialysis patients.',
      hepatic: 'Hepatically synthesised; safe in hepatic disease. Supplementation supports hepatic fat oxidation.',
    },
  },
  {
    id: 'iv-12',
    name: 'Zinc IV (Zinc Sulfate)',
    route: 'IV',
    activeIngredients: [{ name: 'Zinc Sulfate', concentration: '2–4 mg/day in TPN or 10 mg in 100 mL NS' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Zinc deficiency', 'Wound healing', 'Immune support', 'Critical illness', 'Burns', 'Sepsis adjunct', 'Acrodermatitis enteropathica'],
    contraindications: ['Zinc toxicity', 'Copper deficiency (may worsen with high zinc)'],
    interactions: [
      { drug: 'Ciprofloxacin', severity: 'moderate', description: 'Zinc chelates fluoroquinolones, reducing antibiotic absorption; separate by 2 h (oral only concern).' },
      { drug: 'Copper supplements', severity: 'moderate', description: 'High zinc inhibits intestinal copper absorption; monitor copper status.' },
    ],
    sideEffects: ['Nausea/vomiting (rapid IV)', 'Metallic taste', 'Copper depletion (chronic high dose)', 'Fever (contaminant risk)'],
    evidenceSources: ['Prasad AS, Am J Clin Nutr 2007; PMID 17344484', 'ESPEN Micronutrient ICU Guidelines 2022', 'WHO Zinc Supplement Guideline 2021'],
    benefits: 'Co-factor for >300 enzymes. Zinc is essential for wound healing, DNA repair, immune cell signalling, and antioxidant defence (Cu/Zn-SOD). IV replacement achieves rapid correction in malabsorption or critical illness. Systematic evidence supports improved wound healing outcomes, reduced infection duration, and improved immune parameters.',
    organSafety: {
      renal: 'Urinary zinc loss increases in CKD; supplementation often required. Avoid excess in anuric patients.',
      hepatic: 'Wilson\'s disease caution — assess copper status. Otherwise hepatosafe.',
    },
  },
  {
    id: 'iv-13',
    name: 'Taurine IV',
    route: 'IV',
    activeIngredients: [{ name: 'Taurine', concentration: '1–2 g in 100 mL NS' }],
    ebmLevel: 'C',
    ebmCategory: 'Integrative/Empirical',
    indications: ['Heart failure support', 'Diabetic neuropathy', 'Liver protection', 'Hypertension', 'Retinal protection'],
    contraindications: ['Bipolar disorder (may alter osmolyte balance)', 'Known hypersensitivity'],
    interactions: [
      { drug: 'Digoxin', severity: 'minor', description: 'Taurine may have additive effects on cardiac contractility; monitor ECG.' },
      { drug: 'Lithium', severity: 'minor', description: 'Both influence osmotic balance; monitor serum lithium.' },
    ],
    sideEffects: ['Generally very well tolerated', 'Mild hypotension (high IV dose)', 'Nausea'],
    evidenceSources: ['Militante JD, Nutr Res 2002; PMID 12117543', 'Zhang M, Amino Acids 2004; PMID 14594671', 'Integrative Cardiology Monograph 2022'],
    benefits: 'Conditionally essential amino acid with multiple cardiac, neurological, and hepatic roles. Stabilises membrane potentials, regulates intracellular calcium, and acts as an osmoregulator. Japanese cardiologists use IV taurine as standard adjunct in heart failure. Evidence suggests modest reductions in BP and improved exercise tolerance.',
    organSafety: {
      renal: 'Safe across renal function ranges. Renal handling preserves taurine homeostasis.',
      hepatic: 'Hepatoprotective via bile salt conjugation and antioxidant mechanisms. Beneficial in hepatic conditions.',
    },
  },
  {
    id: 'iv-14',
    name: 'Coenzyme Q10 IV (Ubiquinone)',
    route: 'IV',
    activeIngredients: [{ name: 'CoQ10 (Ubiquinone)', concentration: '60–300 mg in lipid emulsion' }],
    ebmLevel: 'C',
    ebmCategory: 'Integrative/Empirical',
    indications: ['Statin-induced myopathy', 'Heart failure (NYHA II–III)', 'Mitochondrial disorders', 'Migraine prophylaxis', 'Post-cardiac surgery'],
    contraindications: ['Insulin-dependent diabetes (may alter glucose regulation)', 'Warfarin (significant interaction)'],
    interactions: [
      { drug: 'Warfarin', severity: 'major', description: 'CoQ10 structurally resembles Vitamin K2; may significantly reduce INR. Monitor INR weekly on initiation.' },
      { drug: 'Statins', severity: 'moderate', description: 'Statins deplete CoQ10; supplementation is indicated — not contraindicated — in statin users.' },
      { drug: 'Antihypertensives', severity: 'moderate', description: 'CoQ10 may have modest BP-lowering effect; monitor for additive hypotension.' },
    ],
    sideEffects: ['Nausea', 'GI upset', 'Insomnia (if given late)', 'Rash (rare)'],
    evidenceSources: ['Mortensen SA et al., JACC Heart Fail 2014; PMID 24943009 (Q-SYMBIO trial)', 'Rosenfeldt FL, J Card Fail 2007; PMID 17338974', 'Integrative Cardiology Society 2023'],
    benefits: 'Essential component of the mitochondrial electron transport chain (Complex I, II, III). Statins deplete CoQ10 by up to 40% via HMG-CoA reductase inhibition. Q-SYMBIO RCT: CoQ10 300 mg/day reduced major adverse cardiovascular events in HF patients. IV form achieves higher bioavailability than oral for acute supplementation.',
    organSafety: {
      renal: 'Safe. Not renally dose-adjusted. Lipid formulation may require caution in severe dyslipidaemia.',
      hepatic: 'Hepatically metabolised. No significant hepatotoxicity. May improve hepatic mitochondrial function.',
    },
  },
  {
    id: 'iv-15',
    name: 'Nano-Curcumin IV',
    route: 'IV',
    activeIngredients: [{ name: 'Nano-encapsulated Curcumin', concentration: '200–500 mg in lipid nanoparticle carrier' }],
    ebmLevel: 'C',
    ebmCategory: 'Integrative/Empirical',
    indications: ['Inflammatory conditions', 'Cancer adjunct support', 'Rheumatoid arthritis', 'Inflammatory bowel disease', 'Neuroprotection'],
    contraindications: ['Biliary obstruction', 'Gallstones (choleretic effect)', 'Pre-surgery (antiplatelet effect)'],
    interactions: [
      { drug: 'Warfarin', severity: 'major', description: 'Curcumin inhibits platelet aggregation and may enhance anticoagulant effect significantly; frequent INR monitoring.' },
      { drug: 'Metformin', severity: 'minor', description: 'Curcumin may enhance metformin uptake via AMPK activation; monitor glucose.' },
      { drug: 'Cyclophosphamide', severity: 'moderate', description: 'May modulate CYP3A4 and reduce cyclophosphamide efficacy; oncology consult required.' },
    ],
    sideEffects: ['Nausea', 'Diarrhoea (bolus)', 'Allergic reaction (nanoparticle carrier)', 'Transient LFT elevation'],
    evidenceSources: ['Prasad S et al., Trends Mol Med 2014; PMID 24931549', 'He ZY et al., Mol Ther 2010; PMID 20389289', 'Integrative Oncology Monograph 2022'],
    benefits: 'Curcuminoid polyphenol with pleiotropic anti-inflammatory, antioxidant, and anti-neoplastic mechanisms. Nano-formulation overcomes poor oral bioavailability (~1%). Inhibits NF-κB, COX-2, and pro-inflammatory cytokines. Preclinical and early clinical evidence in cancer and autoimmune conditions. IV delivery achieves therapeutic tissue concentrations.',
    organSafety: {
      renal: 'Limited renal data for IV nano-form. Use caution in CKD stages 3–4. Standard oral curcumin is renal-safe.',
      hepatic: 'Choleretic — avoid in biliary obstruction. May mildly elevate ALT transiently. Hepatoprotective at low-moderate doses.',
    },
  },
  {
    id: 'iv-16',
    name: 'L-Arginine IV',
    route: 'IV',
    activeIngredients: [{ name: 'L-Arginine HCl', concentration: '8–30 g in 100 mL NS' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Pulmonary arterial hypertension', 'Wound healing', 'Immune support', 'Urea cycle disorders', 'Erectile dysfunction (systemic)'],
    contraindications: ['Active herpes simplex infection (arginine promotes HSV replication)', 'Liver cirrhosis (ammonia accumulation risk)', 'Recent myocardial infarction'],
    interactions: [
      { drug: 'ACE inhibitors', severity: 'moderate', description: 'Additive vasodilation via NO pathway; monitor BP closely.' },
      { drug: 'Sildenafil', severity: 'major', description: 'Both enhance NO-cGMP pathway; profound hypotension risk — avoid concurrent use.' },
      { drug: 'Potassium-sparing diuretics', severity: 'moderate', description: 'Arginine HCl may cause hyperkalemia; monitor electrolytes.' },
    ],
    sideEffects: ['Hypotension', 'Hyperkalemia (HCl salt)', 'Nausea', 'Exacerbation of herpes', 'Hypoglycemia (stimulates insulin)'],
    evidenceSources: ['Böger RH, Cardiovasc Drug Rev 2003; PMID 12728177', 'Kharitonov SA, Lancet 1995; PMID 7898223', 'ESC PAH Guidelines 2022'],
    benefits: 'Substrate for endothelial nitric oxide synthase (eNOS). IV arginine acutely raises nitric oxide, producing vasodilation and improved microvascular perfusion. Level B evidence in pulmonary arterial hypertension. Enhances wound healing via polyamine synthesis and collagen deposition. Essential for immune cell function.',
    organSafety: {
      renal: 'Use with caution in advanced CKD — reduces renal efferent tone. May be protective in early diabetic nephropathy.',
      hepatic: 'Contraindicated in cirrhosis — ammonia accumulation risk via urea cycle flooding.',
    },
  },
  {
    id: 'iv-17',
    name: 'Riboflavin IV (Vitamin B2)',
    route: 'IV',
    activeIngredients: [{ name: 'Riboflavin-5-phosphate', concentration: '25–100 mg in 50 mL NS' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Migraine prophylaxis', 'Riboflavin deficiency', 'MELAS syndrome', 'Mitochondrial complex I/II dysfunction', 'Corneal ectasia (UV cross-linking adjunct)'],
    contraindications: ['Photosensitivity disorders (requires light protection during infusion)'],
    interactions: [
      { drug: 'Tricyclic antidepressants', severity: 'minor', description: 'TCAs may impair riboflavin utilisation; supplementation corrects this.' },
      { drug: 'Methotrexate', severity: 'moderate', description: 'Riboflavin supports folate metabolism; may modulate MTX effects.' },
    ],
    sideEffects: ['Urine discolouration (bright yellow — benign)', 'Photosensitisation', 'Nausea'],
    evidenceSources: ['Schoenen J, Neurology 1998; PMID 9448297', 'MacLennan SC, J Child Neurol 2008; PMID 18024880', 'Cochrane Review Migraine Prophylaxis 2019'],
    benefits: 'B2 is a co-precursor for FAD and FMN — essential cofactors for complex I and II of the mitochondrial respiratory chain. Level B evidence from Schoenen RCT: 400 mg riboflavin daily reduced migraine frequency by 50% vs 15% placebo. IV form used in acute deficiency or when oral absorption is impaired.',
    organSafety: {
      renal: 'Entirely water-soluble; safe in all CKD stages at therapeutic doses. Excess renally excreted.',
      hepatic: 'Hepatically converted to FMN/FAD. Essential for hepatic flavoprotein function. Hepatosafe.',
    },
  },
  {
    id: 'iv-18',
    name: 'Ozone Major Autohemotherapy (O3-MAH)',
    route: 'IV',
    activeIngredients: [{ name: 'Medical-grade Ozone/Oxygen mixture', concentration: '20–40 mcg/mL ozone, 100–200 mL blood' }],
    ebmLevel: 'C',
    ebmCategory: 'Integrative/Empirical',
    indications: ['Chronic limb ischaemia', 'Diabetic foot ulcer adjunct', 'Chronic viral hepatitis', 'Musculoskeletal pain', 'Immune modulation'],
    contraindications: ['Glucose-6-phosphate dehydrogenase (G6PD) deficiency', 'Hyperthyroidism', 'Thrombocytopaenia', 'Haemophilia', 'Pregnancy'],
    interactions: [
      { drug: 'Anticoagulants', severity: 'moderate', description: 'Blood withdrawal for autohemotherapy requires monitored anticoagulation status.' },
      { drug: 'Antioxidant supplements', severity: 'minor', description: 'High-dose antioxidants may blunt ozone hormetic oxidative stimulus.' },
    ],
    sideEffects: ['Mild Herxheimer reaction', 'Phlebitis at withdrawal site', 'Air embolism (if IV direct — contraindicated; only autohemotherapy permitted)', 'Fatigue post-session'],
    evidenceSources: ['Re L, J Exp Integr Med 2014', 'Braidy N, Front Aging Neurosci 2018; PMID 30524256', 'ISCO3 Consensus Guidelines 2015'],
    benefits: 'Oxidative pre-conditioning therapy. Ozone reacts with blood components to produce lipid oxidation products (LOPs) that act as secondary messengers, stimulating antioxidant enzyme upregulation (SOD, GPx), improved erythrocyte deformability, and immune modulation. ISCO3 guidelines describe application protocols for diabetic foot and chronic ischaemia.',
    organSafety: {
      renal: 'Only autohemotherapy route is safe. Direct IV ozone injection is dangerous and prohibited. Safe in stable CKD.',
      hepatic: 'Emerging data in HBV/HCV — possible reduction in viral load and hepatic inflammation. Hepatosafe when dosed correctly.',
    },
    adminNotes: 'ONLY via autohemotherapy protocol. Direct IV ozone injection is absolutely contraindicated. Must be performed by trained practitioner.',
  },
  {
    id: 'iv-19',
    name: 'DMSO IV (Dimethyl Sulfoxide)',
    route: 'IV',
    activeIngredients: [{ name: 'Dimethyl Sulfoxide', concentration: '0.1–0.5 g/kg in 250 mL NS (5–10% solution)' }],
    ebmLevel: 'D',
    ebmCategory: 'Integrative/Empirical',
    indications: ['Amyloidosis adjunct (empirical)', 'Bladder instillation (FDA-approved for IC)', 'Traumatic brain injury (experimental)', 'Cerebral oedema reduction'],
    contraindications: ['Liver disease', 'Renal impairment (eGFR < 45)', 'Pregnancy', 'Sulphur allergy'],
    interactions: [
      { drug: 'Sulindac', severity: 'major', description: 'DMSO reduces sulindac to toxic sulphide metabolite; concurrent use is contraindicated.' },
      { drug: 'Multiple drugs', severity: 'moderate', description: 'DMSO potently enhances transdermal absorption of co-administered drugs; extreme caution.' },
    ],
    sideEffects: ['Garlic/oyster body odour (persistent)', 'Haemolysis (IV, dose-dependent)', 'Nausea', 'Hepatotoxicity (high dose)', 'Haematuria', 'Vision changes'],
    evidenceSources: ['Jacob SW, JAMA 1965 (historical)', 'Santos NC, Eur Biophys J 2003; PMID 12684711', 'FDA Bladder Instillation Approval 1978'],
    benefits: 'Potent biological solvent and hydroxyl radical scavenger. FDA-approved for intravesical use in interstitial cystitis only. IV use is experimental, controversial, and not part of standard integrative practice. Level D evidence only; primarily case reports and historical series.',
    organSafety: {
      renal: 'Significant renal toxicity at IV doses — haematuria risk. Contraindicated eGFR < 45.',
      hepatic: 'Dose-dependent hepatotoxicity. Contraindicated in liver disease. LFT monitoring mandatory.',
    },
    adminNotes: 'IV DMSO is experimental and high-risk. Clinical use should be restricted to investigational protocols only.',
  },
  {
    id: 'iv-20',
    name: 'Hydrogen Peroxide IV (H2O2)',
    route: 'IV',
    activeIngredients: [{ name: 'Hydrogen Peroxide', concentration: '0.0375% (dilute) in NS — highly controversial' }],
    ebmLevel: 'D',
    ebmCategory: 'Integrative/Empirical',
    indications: ['Claimed: immune stimulation (empirical only)', 'Claimed: chronic infections (empirical only)'],
    contraindications: ['ALL patients outside strictly controlled research protocols', 'G6PD deficiency', 'Glucose-6-phosphate dehydrogenase deficiency', 'eGFR < 60'],
    interactions: [
      { drug: 'All reducing agents', severity: 'major', description: 'H2O2 reacts violently with reducing agents; incompatible with most IV medications.' },
    ],
    sideEffects: ['Gas embolism (life-threatening)', 'Haemolysis', 'Phlebitis', 'Tissue necrosis', 'Death (reported cases)'],
    evidenceSources: ['FDA Safety Alert on H2O2 IV 2006', 'Farr CH, J ACAM 1988 (historical, no RCT data)', 'Case reports of fatality: Fintelmann V, Dtsch Med Wochenschr 2006'],
    benefits: 'No validated clinical benefit from IV H2O2 has been demonstrated in controlled trials. Historical empirical use only. The FDA has issued safety warnings regarding life-threatening adverse events including fatal gas embolism.',
    organSafety: {
      renal: 'Renal toxicity from oxidative damage. Not recommended in any eGFR range outside investigational use.',
      hepatic: 'Hepatotoxic via oxidative stress.',
    },
    adminNotes: 'EXTREME CAUTION: IV H2O2 has caused fatalities. This preparation is included for completeness only. Its use is not endorsed by standard integrative or conventional medicine guidelines.',
  },

  // ─── PO PREPARATIONS (30) ─────────────────────────────────────────────────
  {
    id: 'po-01',
    name: 'Magnesium Glycinate PO',
    route: 'PO',
    activeIngredients: [{ name: 'Magnesium Glycinate', concentration: '200–400 mg elemental Mg/day' }],
    ebmLevel: 'A',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Hypomagnesemia', 'Insomnia', 'Anxiety', 'Muscle cramps', 'Migraine prophylaxis', 'Constipation', 'Hypertension adjunct'],
    contraindications: ['eGFR < 30 (without monitoring)', 'Hypermagnesemia', 'Myasthenia gravis'],
    interactions: [
      { drug: 'Bisphosphonates', severity: 'moderate', description: 'Magnesium reduces bisphosphonate absorption; separate by 2 hours.' },
      { drug: 'Quinolones/Tetracyclines', severity: 'moderate', description: 'Chelation reduces antibiotic absorption; separate administration by at least 2 hours.' },
      { drug: 'Levothyroxine', severity: 'moderate', description: 'Reduces T4 absorption; take levothyroxine 4 h before magnesium.' },
    ],
    sideEffects: ['Diarrhoea (less than oxide form)', 'Nausea', 'Abdominal cramping'],
    evidenceSources: ['Volpe SL, Nutr Rev 2013; PMID 23844145', 'Abbasi B, J Res Med Sci 2012; PMID 23329163', 'EMA Magnesium Monograph 2021'],
    benefits: 'Glycinate chelate form offers superior absorption and GI tolerability versus magnesium oxide. Magnesium is cofactor in ATP synthesis, DNA repair, and muscle relaxation. Level A evidence for migraine prophylaxis (200–600 mg/day), sleep quality improvement, and blood pressure reduction.',
    organSafety: {
      renal: 'Monitor serum Mg in eGFR < 30. Renally excreted — risk of accumulation in advanced CKD.',
      hepatic: 'Hepatosafe. No hepatic dose adjustment required.',
    },
  },
  {
    id: 'po-02',
    name: 'Curcumin Extract PO (Bioavailable)',
    route: 'PO',
    activeIngredients: [{ name: 'Curcuminoids (as Meriva or BCM-95)', concentration: '500–1000 mg/day' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Osteoarthritis', 'Rheumatoid arthritis', 'Inflammatory bowel disease', 'Metabolic syndrome', 'NAFLD', 'Cancer adjunct'],
    contraindications: ['Biliary obstruction', 'Gallstones (symptomatic)', 'Pre-operative (antiplatelet)'],
    interactions: [
      { drug: 'Warfarin', severity: 'major', description: 'Inhibits platelet aggregation and CYP2C9; significantly potentiates anticoagulation. Frequent INR monitoring.' },
      { drug: 'Metformin', severity: 'minor', description: 'AMPK activation may be additive; monitor glucose.' },
      { drug: 'Tacrolimus', severity: 'major', description: 'Inhibits CYP3A4 and P-glycoprotein; may dramatically increase tacrolimus levels — avoid.' },
    ],
    sideEffects: ['GI upset (high doses)', 'Nausea', 'Yellow staining of teeth', 'Transient ALT elevation'],
    evidenceSources: ['Kuptniratsaikul V, J Altern Complement Med 2009; PMID 19678781', 'Sahebkar A, Crit Rev Food Sci Nutr 2013; PMID 23710634', 'Phytochemistry Society of Europe 2023'],
    benefits: 'Polyphenolic anti-inflammatory via NF-κB and COX-2 pathway inhibition. Level B RCT data for OA pain comparable to ibuprofen (500 mg Meriva). Bioavailable formulations (phospholipid complex, piperine-enhanced) overcome <1% plain curcumin absorption. NAFLD: multiple RCTs show hepatic enzyme normalisation.',
    organSafety: {
      renal: 'Safe at standard doses. May reduce renal inflammation. Use cautiously in known oxalate nephrolithiasis.',
      hepatic: 'Hepatoprotective at therapeutic doses. Choleretic — stimulates bile flow. Avoid in biliary obstruction.',
    },
  },
  {
    id: 'po-03',
    name: 'Omega-3 Fatty Acids PO (EPA/DHA)',
    route: 'PO',
    activeIngredients: [
      { name: 'EPA (Eicosapentaenoic acid)', concentration: '1–2 g/day' },
      { name: 'DHA (Docosahexaenoic acid)', concentration: '500 mg–1 g/day' },
    ],
    ebmLevel: 'A',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Hypertriglyceridaemia', 'Cardiovascular prevention', 'Inflammatory conditions', 'Depression adjunct', 'Cognitive decline', 'NAFLD', 'Rheumatoid arthritis'],
    contraindications: ['Fish or shellfish allergy (fish-derived)', 'Pre-operative anticoagulation concern'],
    interactions: [
      { drug: 'Warfarin', severity: 'moderate', description: 'High-dose Omega-3 (>3 g/day) may potentiate anticoagulant effect; monitor INR.' },
      { drug: 'Aspirin', severity: 'minor', description: 'Additive antiplatelet effect at high doses; generally safe but monitor in bleeding-prone patients.' },
      { drug: 'Antihypertensives', severity: 'minor', description: 'Omega-3 has modest BP-lowering effect; may add to antihypertensive therapy.' },
    ],
    sideEffects: ['Fishy burps (choose enteric-coated)', 'GI upset', 'Increased LDL (DHA at high dose)', 'Mild bleeding tendency'],
    evidenceSources: ['REDUCE-IT Trial (Bhatt DL, NEJM 2019; PMID 30415628)', 'ESC/EAS Dyslipidaemia Guidelines 2019', 'Cochrane Omega-3 CVD Review 2020'],
    benefits: 'Level A evidence (REDUCE-IT): 4 g/day icosapentaenoic acid reduced major cardiovascular events by 25% in high-risk patients with hypertriglyceridaemia. Resolvin and protectin biosynthesis drives active inflammation resolution. Meta-analyses confirm TG reduction of 20–30% at 3–4 g/day. DHA supports neuronal membrane fluidity and cognitive function.',
    organSafety: {
      renal: 'Safe in CKD. May have renoprotective anti-inflammatory effects. No dose adjustment needed.',
      hepatic: 'Beneficial in NAFLD — multiple RCTs show reduction in hepatic fat, ALT, AST. Hepatosafe.',
    },
  },
  {
    id: 'po-04',
    name: 'Vitamin D3 PO (Cholecalciferol)',
    route: 'PO',
    activeIngredients: [{ name: 'Cholecalciferol (D3)', concentration: '1000–5000 IU/day' }],
    ebmLevel: 'A',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Vitamin D deficiency', 'Osteoporosis prevention', 'Immune modulation', 'Autoimmune disease adjunct', 'Seasonal affective disorder', 'Muscle weakness', 'Cardiovascular risk reduction'],
    contraindications: ['Hypercalcemia', 'Sarcoidosis', 'Granulomatous diseases', 'Primary hyperparathyroidism'],
    interactions: [
      { drug: 'Thiazide diuretics', severity: 'moderate', description: 'Additive hypercalcemia risk; monitor calcium.' },
      { drug: 'Orlistat', severity: 'moderate', description: 'Reduces fat-soluble vitamin D absorption by ~30%; take separately.' },
      { drug: 'Cholestyramine', severity: 'moderate', description: 'Reduces Vit D absorption; take 4 h apart.' },
    ],
    sideEffects: ['Hypercalcemia (overdose > 10,000 IU/day)', 'Hypercalciuria', 'Constipation', 'Fatigue (paradoxical, early)'],
    evidenceSources: ['Holick MF, NEJM 2007; PMID 17634462', 'Endocrine Society Clinical Practice Guideline 2023', 'VITAL Trial, NEJM 2019; PMID 30415610'],
    benefits: 'Second most common nutritional deficiency globally. Level A evidence for fracture prevention (with calcium), immune regulation, and all-cause mortality reduction. Vitamin D receptor present in virtually all cell types. Supplementation reduces autoimmune disease risk (VITAL trial). Target 25-OH-D3: 40–60 ng/mL.',
    organSafety: {
      renal: 'Activated to calcitriol by 1-alpha-hydroxylase in kidney — impaired in CKD stages 3–5; use calcitriol directly in advanced CKD.',
      hepatic: '25-hydroxylation occurs in liver. Severe hepatic failure impairs conversion. Use calcitriol in decompensated cirrhosis.',
    },
  },
  {
    id: 'po-05',
    name: 'B12 Methylcobalamin PO',
    route: 'PO',
    activeIngredients: [{ name: 'Methylcobalamin', concentration: '500–1000 mcg/day (sublingual or oral)' }],
    ebmLevel: 'A',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['B12 deficiency', 'Pernicious anaemia (sublingual)', 'Peripheral neuropathy', 'Cognitive decline', 'Depression adjunct', 'Metformin-induced B12 depletion', 'MTHFR mutations'],
    contraindications: ['Hypersensitivity to cobalamin', 'Leber\'s hereditary optic neuropathy'],
    interactions: [
      { drug: 'Metformin', severity: 'moderate', description: 'Metformin reduces ileal B12 absorption by up to 30%; supplementation is recommended.' },
      { drug: 'Omeprazole/PPIs', severity: 'moderate', description: 'Chronic PPI use impairs B12 absorption; supplementation indicated.' },
    ],
    sideEffects: ['Generally very well tolerated', 'Acneiform rash (rare)', 'Urine discolouration (harmless)'],
    evidenceSources: ['Toh BH, NEJM 2009; PMID 19846853', 'NHS/NICE B12 Deficiency Guideline 2023', 'Sobczyńska-Malefora A, JIFCC 2021'],
    benefits: 'Active methylated form of B12 — preferred over cyanocobalamin for neurological applications. Methylcobalamin donates methyl groups in homocysteine remethylation and SAMe synthesis. Level A evidence for correcting deficiency anaemia and neuropathy. Sublingual achieves similar bioavailability to IM in B12-deficient patients with intact intrinsic factor.',
    organSafety: {
      renal: 'Water-soluble; safe in all CKD stages. Elevated homocysteine in CKD is corrected by B12/folate supplementation.',
      hepatic: 'Stored in liver. Hepatosafe. Hepatic disease may impair B12 storage capacity.',
    },
  },
  {
    id: 'po-06',
    name: 'Methylfolate PO (5-MTHF)',
    route: 'PO',
    activeIngredients: [{ name: '5-Methyltetrahydrofolate (5-MTHF)', concentration: '400–5000 mcg/day' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Folate deficiency', 'MTHFR polymorphism', 'Hyperhomocysteinaemia', 'Depression adjunct', 'Pregnancy (neural tube prevention)', 'Cardiovascular risk reduction'],
    contraindications: ['B12 deficiency undiagnosed (may mask macrocytic anaemia)'],
    interactions: [
      { drug: 'Methotrexate', severity: 'major', description: 'Folate supplementation during MTX therapy requires oncology/rheumatology direction — timing is critical.' },
      { drug: 'Anticonvulsants (Phenytoin, Valproate)', severity: 'moderate', description: 'Anticonvulsants reduce serum folate; supplementation may lower seizure threshold slightly in uncontrolled epilepsy.' },
    ],
    sideEffects: ['Agitation (in some with MTHFR)', 'Insomnia', 'GI upset', 'Masking of B12 deficiency (if used alone)'],
    evidenceSources: ['Greenberg JA, Rev Obstet Gynecol 2011; PMID 22866186', 'Stahl SM, CNS Spectr 2008; PMID 18419374', 'European Journal of Nutrition Folate Review 2023'],
    benefits: 'Active form bypasses MTHFR enzymatic conversion — critical for patients with C677T/A1298C polymorphisms who cannot effectively convert dietary folate. Supports methylation cycle, homocysteine control, monoamine neurotransmitter synthesis. Level B evidence as adjunct in depression (L-methylfolate 15 mg/day improved SSRI response in 2 RCTs).',
    organSafety: {
      renal: 'Water-soluble; safe in CKD. Elevated homocysteine in CKD benefits from folate/B12 combination.',
      hepatic: 'Hepatically processed; safe in mild-moderate liver disease.',
    },
  },
  {
    id: 'po-07',
    name: 'CoQ10 Ubiquinol PO',
    route: 'PO',
    activeIngredients: [{ name: 'Ubiquinol (reduced CoQ10)', concentration: '100–300 mg/day' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Statin-induced myopathy', 'Heart failure (NYHA II–III)', 'Migraine prophylaxis', 'Male fertility', 'Parkinson\'s adjunct', 'Mitochondrial disorders', 'Hypertension'],
    contraindications: ['None absolute; caution with Warfarin'],
    interactions: [
      { drug: 'Warfarin', severity: 'major', description: 'Structurally similar to Vitamin K2; may reduce INR substantially. Strict INR monitoring weekly on initiation.' },
      { drug: 'Antihypertensives', severity: 'moderate', description: 'Additive BP lowering at 100–300 mg/day; monitor BP.' },
      { drug: 'Chemotherapy (doxorubicin)', severity: 'moderate', description: 'May reduce anthracycline cardiotoxicity — potential benefit; oncology review required.' },
    ],
    sideEffects: ['GI upset', 'Insomnia (if taken at night)', 'Elevated LFTs (rare)', 'Headache'],
    evidenceSources: ['Mortensen SA, JACC Heart Fail 2014; PMID 24943009 (Q-SYMBIO)', 'Sander S, Ann Pharmacother 2006; PMID 16548555', 'Cochrane CoQ10 HF Review 2021'],
    benefits: 'Ubiquinol (reduced form) has 2–8× better oral bioavailability than ubiquinone. Essential mitochondrial electron carrier. Statin drugs reduce CoQ10 biosynthesis by up to 40%. Q-SYMBIO trial: 300 mg/day reduced all-cause mortality and major adverse cardiac events in heart failure. Migraine: several RCTs show >50% reduction in attack frequency.',
    organSafety: {
      renal: 'Hepatically metabolised; not renally dose-dependent. Safe in CKD.',
      hepatic: 'Generally hepatosafe. Rare cases of mild transaminase elevation at very high doses (>600 mg/day).',
    },
  },
  {
    id: 'po-08',
    name: 'N-Acetyl Cysteine (NAC) PO',
    route: 'PO',
    activeIngredients: [{ name: 'N-Acetyl-L-Cysteine', concentration: '600–1800 mg/day' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Acetaminophen toxicity (gold standard)', 'Chronic bronchitis/COPD', 'NAFLD', 'Polycystic ovary syndrome', 'Psychiatric disorders (OCD adjunct)', 'Contrast nephropathy prevention', 'Glutathione precursor'],
    contraindications: ['Asthma (may provoke bronchospasm orally, though inhaled concern)', 'Active peptic ulcer disease'],
    interactions: [
      { drug: 'Nitrates', severity: 'moderate', description: 'Additive vasodilation; may cause severe hypotension and headache.' },
      { drug: 'Activated charcoal', severity: 'major', description: 'Charcoal adsorbs NAC; administer IV or delay charcoal by 2 hours in overdose.' },
      { drug: 'Carbamazepine', severity: 'minor', description: 'NAC may modulate redox pathways relevant to anticonvulsant effect.' },
    ],
    sideEffects: ['Nausea', 'Vomiting', 'Diarrhoea', 'Rash', 'Stomatitis (high doses)'],
    evidenceSources: ['Kernan WN, Stroke 2006; PMID 16484610', 'Stey C, Eur Resp J 2000; PMID 10967000', 'Cochrane NAC COPD Review 2022'],
    benefits: 'Rate-limiting precursor for intracellular glutathione (GSH) synthesis. Level B evidence for reduction of COPD exacerbations (600–1200 mg/day), NAFLD improvement, and contrast nephropathy prevention. Acetylcysteine is the standard antidote for paracetamol (acetaminophen) toxicity. Emerging evidence in PCOS, addiction, and psychiatric conditions.',
    organSafety: {
      renal: 'Nephroprotective in contrast nephropathy. Safe in CKD. Glutathione support beneficial in renal oxidative stress.',
      hepatic: 'Specifically hepatoprotective via glutathione repletion. First-line in paracetamol-induced hepatotoxicity.',
    },
  },
  {
    id: 'po-09',
    name: 'Berberine PO',
    route: 'PO',
    activeIngredients: [{ name: 'Berberine HCl', concentration: '500–1500 mg/day (in divided doses)' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Type 2 Diabetes', 'Dyslipidaemia', 'Metabolic syndrome', 'PCOS', 'NAFLD', 'Hypertension', 'SIBO'],
    contraindications: ['Pregnancy (oxytocic effect)', 'Neonates/infants (kernicterus risk)', 'Severe hepatic failure'],
    interactions: [
      { drug: 'Metformin', severity: 'moderate', description: 'Additive glucose-lowering via AMPK activation; significant hypoglycemia risk — monitor closely.' },
      { drug: 'Warfarin', severity: 'moderate', description: 'Inhibits CYP2C9; may significantly increase warfarin levels. Frequent INR monitoring.' },
      { drug: 'Cyclosporine', severity: 'major', description: 'Inhibits P-glycoprotein and CYP3A4; may drastically increase cyclosporine levels.' },
      { drug: 'Statins', severity: 'moderate', description: 'Inhibits CYP3A4 — may raise statin plasma levels; monitor for myopathy.' },
    ],
    sideEffects: ['GI upset (constipation or diarrhoea)', 'Nausea', 'Hypoglycemia (combination therapy)', 'Yellow skin (high doses, harmless)'],
    evidenceSources: ['Zhang Y, J Clin Endocrinol Metab 2008; PMID 18445558', 'Dong H, Evid Based Complement Altern Med 2012; PMID 22228000', 'ADA Standards of Diabetes Care 2023 (mentions berberine)'],
    benefits: 'Isoquinoline alkaloid with comparable glucose-lowering effect to metformin in 2 head-to-head RCTs (HbA1c reduction ~1%). AMPK activator — improves insulin sensitivity, reduces hepatic glucose output, and lowers LDL via PCSK9 inhibition pathway. Multiple meta-analyses confirm lipid-lowering superiority to placebo.',
    organSafety: {
      renal: 'Generally safe. Some evidence of renal-protective anti-inflammatory effects in diabetic nephropathy.',
      hepatic: 'Caution in severe hepatic failure. At therapeutic doses, shown to reduce hepatic steatosis in NAFLD.',
    },
  },
  {
    id: 'po-10',
    name: 'Ashwagandha PO (KSM-66)',
    route: 'PO',
    activeIngredients: [{ name: 'Withania somnifera root extract (KSM-66)', concentration: '300–600 mg/day' }],
    ebmLevel: 'C',
    ebmCategory: 'Integrative/Empirical',
    indications: ['Chronic stress', 'Anxiety', 'Adrenal fatigue', 'Male hypogonadism (adjunct)', 'Athletic performance', 'Thyroid support', 'Insomnia', 'Cognitive function'],
    contraindications: ['Autoimmune thyroid disease (Hashimoto\'s) with active hyperthyroidism', 'Pregnancy', 'Hormone-sensitive cancers (theoretical)', 'Nightshade allergy'],
    interactions: [
      { drug: 'Levothyroxine', severity: 'moderate', description: 'Ashwagandha may increase T3/T4; monitor TFTs if adding to thyroid hormone therapy.' },
      { drug: 'Immunosuppressants', severity: 'moderate', description: 'Ashwagandha stimulates immune activity; may reduce immunosuppressant efficacy.' },
      { drug: 'Benzodiazepines', severity: 'moderate', description: 'Additive CNS sedation; reduce benzodiazepine dose cautiously.' },
    ],
    sideEffects: ['GI upset', 'Drowsiness', 'Elevated TFTs (case reports)', 'Rare liver injury (case reports at high doses)', 'Nightshade hypersensitivity'],
    evidenceSources: ['Chandrasekhar K, Indian J Psychol Med 2012; PMID 23439798', 'Wankhede S, J Int Soc Sports Nutr 2015; PMID 26609282', 'Integrative Herbology Monograph 2022'],
    benefits: 'Adaptogenic herb classified as Rasayana in Ayurveda. KSM-66 is the most studied root extract. RCTs demonstrate significant cortisol reduction (28%), improved stress resilience on PSS scale, testosterone elevation in men, and modest anxiolytic effects. Withanolide glycosides are the bioactive constituents.',
    organSafety: {
      renal: 'Safe at standard doses. No nephrotoxicity in clinical trials.',
      hepatic: 'Rare hepatotoxicity case reports at supraphysiologic doses (>1800 mg/day). Use standard doses. Monitor LFTs if used long-term.',
    },
  },
  {
    id: 'po-11',
    name: 'Alpha-Lipoic Acid PO',
    route: 'PO',
    activeIngredients: [{ name: 'R-Alpha-Lipoic Acid', concentration: '300–600 mg/day' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Diabetic neuropathy', 'Metabolic syndrome', 'Oxidative stress', 'Insulin resistance', 'Weight management adjunct'],
    contraindications: ['Thiamine deficiency', 'Pregnancy (insufficient data)'],
    interactions: [
      { drug: 'Metformin', severity: 'moderate', description: 'Additive glucose-lowering; monitor for hypoglycemia.' },
      { drug: 'Levothyroxine', severity: 'moderate', description: 'May reduce T4 absorption; take 4 h apart.' },
      { drug: 'Chemotherapy agents', severity: 'moderate', description: 'May antagonise platinum agents and alkylating agents via antioxidant mechanism.' },
    ],
    sideEffects: ['Hypoglycemia', 'Nausea', 'Skin rash', 'Thiamine depletion with chronic use'],
    evidenceSources: ['Ziegler D, Diabetologia 1999; PMID 10436966 (ALADIN trial)', 'Packer L, Free Radic Biol Med 1995; PMID 7649494', 'German Diabetes Society Guidelines 2023'],
    benefits: 'Both aqueous and lipid-phase antioxidant. ALADIN trial: ALA 600–1200 mg/day significantly reduced neuropathic pain scores. Improves insulin-stimulated glucose uptake. Regenerates oxidised vitamin C, E, and glutathione. R-form is more biologically active and better absorbed than racemic mixture.',
    organSafety: {
      renal: 'Generally safe. Monitor in severe CKD (eGFR < 15).',
      hepatic: 'Hepatoprotective. May improve NAFLD parameters. Hepatosafe.',
    },
  },
  {
    id: 'po-12',
    name: 'Melatonin PO',
    route: 'PO',
    activeIngredients: [{ name: 'Melatonin', concentration: '0.5–5 mg at bedtime' }],
    ebmLevel: 'A',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Insomnia (sleep-onset)', 'Jet lag', 'Shift-work sleep disorder', 'REM sleep behaviour disorder', 'Antioxidant support', 'Migraine prophylaxis'],
    contraindications: ['Autoimmune diseases (immune-stimulating at high doses)', 'Pregnancy'],
    interactions: [
      { drug: 'Warfarin', severity: 'moderate', description: 'May modestly potentiate anticoagulant effect; monitor INR.' },
      { drug: 'Fluvoxamine (SSRI)', severity: 'major', description: 'CYP1A2 inhibition dramatically raises melatonin levels; avoid or reduce dose to 0.5 mg max.' },
      { drug: 'Benzodiazepines', severity: 'moderate', description: 'Additive sedation; reduce benzodiazepine dose if indicated.' },
    ],
    sideEffects: ['Morning grogginess (high doses)', 'Vivid dreams', 'Headache', 'Mood changes'],
    evidenceSources: ['Brzezinski A, Sleep Med Rev 2005; PMID 15649736', 'Arendt J, Neuropharmacology 2010; PMID 20713077', 'NICE Melatonin Guideline 2022'],
    benefits: 'Endogenous circadian hormone produced by the pineal gland. Level A evidence for sleep-onset latency reduction and jet-lag mitigation. Low doses (0.5 mg) are as effective as pharmacological doses for most applications. Potent free-radical scavenger with specific protection for mitochondrial DNA. NICE recommends 2 mg modified-release for adults >55 with insomnia.',
    organSafety: {
      renal: 'Renally cleared. Dose reduction in severe CKD (start at 0.5 mg). Accumulation possible in ESKD.',
      hepatic: 'CYP1A2 metabolised in liver. Reduce dose in severe hepatic impairment. Half-life doubles in cirrhosis.',
    },
  },
  {
    id: 'po-13',
    name: 'Probiotics Multi-strain PO',
    route: 'PO',
    activeIngredients: [{ name: 'Multi-strain Lactobacillus/Bifidobacterium blend', concentration: '10–50 billion CFU/day' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['IBS', 'Antibiotic-associated diarrhoea', 'IBD (Ulcerative colitis)', 'H. pylori eradication adjunct', 'Immune modulation', 'Vaginal health', 'NAFLD'],
    contraindications: ['Severe immunocompromise (risk of septicaemia)', 'Central venous line in situ', 'Active pancreatitis'],
    interactions: [
      { drug: 'Antibiotics', severity: 'moderate', description: 'Antibiotics kill probiotic organisms; take probiotics 2 h after antibiotics.' },
      { drug: 'Immunosuppressants', severity: 'moderate', description: 'In transplant patients, probiotic bacteraemia is a rare but real risk; use with caution.' },
    ],
    sideEffects: ['Bloating', 'Gas', 'Initial constipation or diarrhoea (adaptation period 1–2 weeks)', 'Rare: septicaemia in immunocompromised'],
    evidenceSources: ['Ford AC, Am J Gastroenterol 2014; PMID 24733982 (Cochrane meta-analysis)', 'McFarland LV, J Med Food 2010; PMID 20230295', 'WHO/FAO Probiotic Guideline 2020'],
    benefits: 'Gut microbiome restoration through exogenous beneficial bacteria. Level B meta-analysis evidence for IBS symptom improvement (NNT 7), antibiotic-associated diarrhoea reduction (NNT 8), and C. difficile prevention. Strain-specific effects: Lactobacillus rhamnosus GG is most studied. Gut-brain axis modulation emerging in anxiety and depression.',
    organSafety: {
      renal: 'Safe in CKD. D-lactic acid-producing strains should be avoided in short-bowel syndrome.',
      hepatic: 'Beneficial in hepatic encephalopathy (reduces ammonia-producing gut bacteria). Level B evidence for NAFLD.',
    },
  },
  {
    id: 'po-14',
    name: 'Zinc Picolinate PO',
    route: 'PO',
    activeIngredients: [{ name: 'Zinc Picolinate', concentration: '15–30 mg elemental zinc/day' }],
    ebmLevel: 'A',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Zinc deficiency', 'Immune support', 'Wound healing', 'Acne', 'ARMD prevention', 'Male fertility', 'Anosmia', 'Testosterone support'],
    contraindications: ['Copper deficiency (monitor)', 'High zinc dietary intake without confirmed deficiency'],
    interactions: [
      { drug: 'Ciprofloxacin', severity: 'moderate', description: 'Zinc chelates quinolones; separate administration by 2 hours.' },
      { drug: 'Tetracyclines', severity: 'moderate', description: 'Mutual chelation reduces absorption of both; take 2 h apart.' },
      { drug: 'Iron supplements', severity: 'moderate', description: 'Compete for intestinal absorption; take at different meal times.' },
    ],
    sideEffects: ['Nausea (take with food)', 'Metallic taste', 'Copper depletion (>50 mg/day chronic)', 'Decreased HDL (high dose)'],
    evidenceSources: ['Prasad AS, J Am Coll Nutr 2009; PMID 19641165', 'AREDS2 Trial, JAMA 2013; PMID 23645227', 'WHO Micronutrient Guidelines 2022'],
    benefits: 'Picolinate chelate is the best-absorbed oral zinc form. Critical for thymosin hormone, zinc-finger protein transcription factors, wound healing, and spermatogenesis. AREDS2 trial: zinc 80 mg/day reduced advanced AMD progression. Prasad RCT: 45 mg/day reduced incidence of infection in elderly. Multiple RCTs confirm reduced common cold duration.',
    organSafety: {
      renal: 'Renally excreted. Safe in mild-moderate CKD. Avoid excess in anuric patients.',
      hepatic: 'Safe. Zinc is hepatoprotective in Wilson\'s disease as copper-displacing agent.',
    },
  },
  {
    id: 'po-15',
    name: 'Iron Bisglycinate PO',
    route: 'PO',
    activeIngredients: [{ name: 'Ferrous Bisglycinate (iron-amino acid chelate)', concentration: '25–50 mg elemental iron/day' }],
    ebmLevel: 'A',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Iron deficiency anaemia', 'Iron deficiency without anaemia', 'Chronic fatigue (iron depletion)', 'Restless legs syndrome', 'Heavy menstrual bleeding', 'Pregnancy'],
    contraindications: ['Haemochromatosis', 'Haemosiderosis', 'Haemolytic anaemia', 'Thalassaemia major'],
    interactions: [
      { drug: 'Levothyroxine', severity: 'major', description: 'Iron dramatically reduces levothyroxine absorption; take 4 h apart.' },
      { drug: 'Proton pump inhibitors', severity: 'moderate', description: 'Reduced gastric acid impairs non-haeme iron absorption; bisglycinate less affected.' },
      { drug: 'Calcium supplements', severity: 'moderate', description: 'Calcium inhibits iron absorption; take at different meal times.' },
      { drug: 'Quinolone antibiotics', severity: 'moderate', description: 'Mutual chelation; separate by 2 h.' },
    ],
    sideEffects: ['Constipation (less than ferrous sulphate)', 'Nausea', 'Dark stools', 'GI cramping', 'Iron overload (excess)'],
    evidenceSources: ['Milman N, Ann Hematol 2012; PMID 22484440', 'Tolkien Z, PLoS ONE 2015; PMID 25764044', 'WHO Guidelines for Iron Deficiency Anaemia 2020'],
    benefits: 'Bisglycinate chelate has 2–4× superior absorption and 4× better GI tolerance than ferrous sulphate, with 90% reduced oxidative damage to GI mucosa. Ferritin repletion is essential for fatigue resolution, thyroid peroxidase function, and dopaminergic pathways (restless legs). Target serum ferritin > 50 mcg/L for symptom resolution.',
    organSafety: {
      renal: 'Safe in mild-moderate CKD. Intravenous iron preferred in dialysis patients; oral bisglycinate is well-tolerated option in non-dialysis CKD.',
      hepatic: 'Avoid in haemochromatosis/haemosiderosis. Monitor ferritin in chronic liver disease — hepatic iron overload worsens fibrosis.',
    },
  },
  {
    id: 'po-16',
    name: 'Vitamin C PO (Ascorbic Acid)',
    route: 'PO',
    activeIngredients: [{ name: 'L-Ascorbic Acid', concentration: '500–2000 mg/day' }],
    ebmLevel: 'A',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Vitamin C deficiency/Scurvy', 'Immune support', 'Collagen synthesis', 'Iron absorption enhancement', 'Antioxidant', 'Cardiovascular protection', 'Common cold reduction'],
    contraindications: ['Oxalate nephrolithiasis', 'Haemochromatosis (increases iron absorption)', 'G6PD deficiency (very high doses)'],
    interactions: [
      { drug: 'Warfarin', severity: 'moderate', description: 'Doses > 1 g/day may affect INR; monitor.' },
      { drug: 'Aluminium-containing antacids', severity: 'minor', description: 'Vitamin C increases aluminium absorption.' },
      { drug: 'Statins', severity: 'minor', description: 'High-dose antioxidants may reduce HDL-raising effect of niacin-statin combinations.' },
    ],
    sideEffects: ['GI upset', 'Diarrhoea (bowel-tolerance limit)', 'Kidney stones (high dose, susceptible individuals)', 'Dental erosion (chewable forms)'],
    evidenceSources: ['Carr AC, Nutrients 2017; PMID 29099763', 'Hemilä H, Cochrane Database 2013; PMID 23440782', 'Endocrine Society Antioxidant Review 2023'],
    benefits: 'Essential water-soluble antioxidant and cofactor for collagen hydroxylases, carnitine biosynthesis, and norepinephrine synthesis. Cochrane meta-analysis: Vit C reduces common cold duration by 8% adults, 14% children. Improves non-haeme iron absorption 3-fold. Plasma saturation occurs at ~200 mg/day; supraphysiologic doses have antioxidant benefits.',
    organSafety: {
      renal: 'Oxalic acid metabolite may crystallise in susceptible patients. Screen for oxalate history. Limit to 500 mg in eGFR < 30.',
      hepatic: 'Hepatosafe. Supports hepatic antioxidant defence.',
    },
  },
  {
    id: 'po-17',
    name: 'Resveratrol PO',
    route: 'PO',
    activeIngredients: [{ name: 'Trans-Resveratrol', concentration: '100–500 mg/day' }],
    ebmLevel: 'C',
    ebmCategory: 'Integrative/Empirical',
    indications: ['Cardiovascular protection', 'Metabolic syndrome', 'Anti-aging (sirtuin activation)', 'NAFLD', 'Type 2 Diabetes adjunct', 'Cancer chemoprotection'],
    contraindications: ['Oestrogen-receptor positive cancers (weak phytooestrogenic activity)', 'Pre-surgery (antiplatelet)'],
    interactions: [
      { drug: 'Warfarin', severity: 'moderate', description: 'Inhibits CYP2C9; may increase warfarin levels. Monitor INR.' },
      { drug: 'Statins', severity: 'moderate', description: 'Inhibits CYP3A4; may raise simvastatin/lovastatin levels — monitor.' },
    ],
    sideEffects: ['GI upset', 'Diarrhoea (>1 g/day)', 'Headache', 'Leg pain (high doses)', 'Mild oestrogenic activity'],
    evidenceSources: ['Bhatt JK, Food Chem Toxicol 2012; PMID 22841869', 'Poulsen MM, Diabetes Care 2013; PMID 23382518', 'Review: Springer Nat Aging 2022'],
    benefits: 'Polyphenol activating SIRT1/AMPK pathways — mimics caloric restriction signalling. Inhibits NF-κB, promotes autophagy, extends lifespan in model organisms. Clinical evidence is mixed but promising for glucose lowering in T2DM and hepatic fat in NAFLD. Poor oral bioavailability limits efficacy; micronised or liposomal forms preferred.',
    organSafety: {
      renal: 'Safe in standard doses. Some evidence of renal-protective effects.',
      hepatic: 'Hepatoprotective in NAFLD — reduces hepatic steatosis. Safe in mild liver disease.',
    },
  },
  {
    id: 'po-18',
    name: 'Selenium Methionine PO (SeMet)',
    route: 'PO',
    activeIngredients: [{ name: 'L-Selenomethionine', concentration: '100–200 mcg/day' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Selenium deficiency', 'Hashimoto\'s thyroiditis', 'Male infertility', 'Cancer prevention adjunct', 'Immune support', 'Thyroid autoimmunity'],
    contraindications: ['Selenium adequacy/toxicity', 'Active thyroid cancer (caution — theoretical growth promotion)'],
    interactions: [
      { drug: 'Iodine (potassium iodide)', severity: 'minor', description: 'Synergistic thyroid hormone synthesis support; both required in thyroid conditions.' },
      { drug: 'Statins', severity: 'minor', description: 'Selenium supports CoQ10 activity pathway; complementary in statin myopathy.' },
    ],
    sideEffects: ['Garlic breath (selenosis marker)', 'Hair loss (chronic excess > 400 mcg/day)', 'Nail brittleness', 'GI upset'],
    evidenceSources: ['Mazokopakis EE, Thyroid 2007; PMID 17696828', 'Ventura M, Front Endocrinol 2017; PMID 28243225', 'Rayman MP, Lancet 2012; PMID 21507558'],
    benefits: 'SeMet is the dominant dietary selenium form with highest bioavailability (~90%). Multiple RCTs confirm 200 mcg/day selenomethionine reduces anti-TPO antibody titres in Hashimoto\'s thyroiditis by 30–50%. GPx, thioredoxin reductase, and selenoprotein P require selenium. Essential for male fertility (selenoprotein P in sperm).',
    organSafety: {
      renal: 'Renally excreted. Reduce dose in eGFR < 30 to prevent selenosis.',
      hepatic: 'Supports hepatic GPx and thioredoxin reductase. Safe in standard doses.',
    },
  },
  {
    id: 'po-19',
    name: 'L-Glutamine PO',
    route: 'PO',
    activeIngredients: [{ name: 'L-Glutamine', concentration: '5–20 g/day' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Leaky gut syndrome', 'IBD remission maintenance', 'Post-surgical gut recovery', 'Chemotherapy mucositis', 'Athletic recovery', 'Critical illness (muscle preservation)'],
    contraindications: ['Reye\'s syndrome', 'Cirrhosis with hepatic encephalopathy (glutamine → ammonia)', 'Bipolar disorder (may elevate glutamate)'],
    interactions: [
      { drug: 'Lactulose', severity: 'minor', description: 'Both target GI ammonia; monitor closely in hepatic encephalopathy.' },
      { drug: 'Anticonvulsants', severity: 'moderate', description: 'Glutamine is a glutamate precursor; may alter seizure threshold at high doses.' },
    ],
    sideEffects: ['GI discomfort (>15 g/day)', 'Bloating', 'Elevated ammonia in hepatic encephalopathy', 'Headache'],
    evidenceSources: ['Akobeng AK, J Pediatr Gastroenterol Nutr 2000; PMID 10733190', 'Sacks GS, Pharmacotherapy 1999; PMID 10600080', 'ESPEN Clinical Nutrition Guidelines 2023'],
    benefits: 'Most abundant free amino acid in the body and primary fuel for intestinal enterocytes. Conditionally essential in critical illness and gastrointestinal stress. Level B evidence for mucositis reduction in chemotherapy patients, improved gut barrier function (tight junction upregulation), and preservation of lean muscle mass in critical illness.',
    organSafety: {
      renal: 'Safe in mild CKD. High doses may increase nitrogen load — use cautiously in advanced CKD stages 4–5.',
      hepatic: 'Contraindicated in hepatic encephalopathy — glutamine increases ammonia. Otherwise hepatosafe.',
    },
  },
  {
    id: 'po-20',
    name: 'Acetyl-L-Carnitine PO (ALCAR)',
    route: 'PO',
    activeIngredients: [{ name: 'Acetyl-L-Carnitine HCl', concentration: '500–2000 mg/day' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Peripheral neuropathy (diabetic, chemo-induced)', 'Cognitive decline / mild Alzheimer\'s', 'Depression adjunct', 'Male infertility', 'Chronic fatigue', 'Statin-induced myopathy'],
    contraindications: ['Seizure history (high doses)', 'Thyroid disease (may increase thyroid hormone effect)'],
    interactions: [
      { drug: 'Warfarin', severity: 'moderate', description: 'Carnitine may enhance anticoagulant effect; monitor INR.' },
      { drug: 'Anticonvulsants (Valproate)', severity: 'moderate', description: 'Valproate depletes carnitine; supplementation is beneficial and may be necessary.' },
    ],
    sideEffects: ['Fishy body odour', 'GI upset', 'Restlessness/agitation', 'Insomnia', 'Seizure risk at high doses'],
    evidenceSources: ['Sima AA, Diabetes Care 2005; PMID 15735218', 'Pennisi M, Metabolites 2020; PMID 32455638', 'Italian National Neurological Society Neuropathy Guidelines 2022'],
    benefits: 'Acetylated carnitine that crosses the blood-brain barrier. Donates acetyl groups for acetylcholine synthesis and mitochondrial metabolism. Multiple RCTs demonstrate significant improvement in diabetic neuropathy pain scores and nerve conduction velocity. Cochrane meta-analysis: ALCAR may slow progression of mild cognitive impairment to Alzheimer\'s. Level B evidence for neuropathy and cognition.',
    organSafety: {
      renal: 'Safe in CKD. Haemodialysis patients systematically depleted — supplementation beneficial.',
      hepatic: 'Hepatosafe. Supports hepatic beta-oxidation of fatty acids.',
    },
  },
  {
    id: 'po-21',
    name: 'Phosphatidylserine PO',
    route: 'PO',
    activeIngredients: [{ name: 'Phosphatidylserine (soy-derived)', concentration: '100–400 mg/day' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Cognitive decline', 'ADHD adjunct', 'Stress/cortisol reduction', 'Athletic recovery', 'Alzheimer\'s adjunct'],
    contraindications: ['Soy allergy (soy-derived PS)', 'Anticoagulant therapy (minor concern)'],
    interactions: [
      { drug: 'Anticholinergic drugs', severity: 'minor', description: 'PS may antagonise anticholinergic effects via cholinergic support.' },
      { drug: 'Warfarin', severity: 'minor', description: 'PS has mild antiplatelet activity; monitor INR.' },
    ],
    sideEffects: ['GI upset', 'Insomnia (if taken late)', 'Fishy odour (bovine-derived PS)'],
    evidenceSources: ['Crook TH, Psychopharmacol Bull 1992; PMID 1496154', 'Kidd PM, Altern Med Rev 2003; PMID 14599451', 'EFSA PS Cognition Review 2021'],
    benefits: 'Essential phospholipid comprising 15–20% of total brain phospholipids. Supports synaptic membrane fluidity, nerve growth factor (NGF) signalling, and acetylcholine biosynthesis. FDA qualified health claim for cognitive function. Meta-analyses: 300–400 mg/day improves memory, learning, and concentration in age-related cognitive decline. Reduces post-exercise cortisol by up to 30%.',
    organSafety: {
      renal: 'Safe across all renal function ranges.',
      hepatic: 'Hepatosafe. Phospholipid component supports membrane integrity throughout the body.',
    },
  },
  {
    id: 'po-22',
    name: 'Rhodiola Rosea PO',
    route: 'PO',
    activeIngredients: [{ name: 'Rhodiola Rosea root extract (3% rosavins, 1% salidrosides)', concentration: '200–600 mg/day' }],
    ebmLevel: 'C',
    ebmCategory: 'Integrative/Empirical',
    indications: ['Burnout / work-related stress', 'Chronic fatigue', 'Anxiety', 'Mild depression', 'Athletic performance', 'Altitude sickness'],
    contraindications: ['Bipolar disorder (may trigger mania)', 'Pregnancy', 'Autoimmune conditions (immune-modulating)'],
    interactions: [
      { drug: 'SSRIs/SNRIs', severity: 'moderate', description: 'MAO-inhibitory activity of salidrosides may contribute to serotonin syndrome risk; monitor closely.' },
      { drug: 'Diabetic medications', severity: 'minor', description: 'May modestly lower blood glucose; monitor fasting glucose.' },
    ],
    sideEffects: ['Agitation', 'Insomnia (take before noon)', 'Dry mouth', 'Dizziness'],
    evidenceSources: ['Darbinyan V, Phytomedicine 2000; PMID 11081987', 'Olsson EM, Planta Med 2009; PMID 19016404', 'HMPC European Medicines Agency Monograph 2012'],
    benefits: 'Siberian adaptogen validated by EMA as traditional herbal medicine for stress and fatigue. Rosavins and salidrosides modulate HPA axis stress response, reduce cortisol, improve cognitive performance under fatigue. Phase 3-like trial (Olsson 2009): 576 mg/day improved burnout symptoms significantly vs placebo after 12 weeks.',
    organSafety: {
      renal: 'Safe in standard doses. No nephrotoxicity reported.',
      hepatic: 'Hepatosafe in clinical trials. Rare anecdotal liver reports at very high doses.',
    },
  },
  {
    id: 'po-23',
    name: 'Milk Thistle PO (Silymarin 80%)',
    route: 'PO',
    activeIngredients: [{ name: 'Silymarin (80% standardised extract)', concentration: '140–420 mg/day' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['NAFLD', 'Alcoholic liver disease', 'Drug-induced hepatotoxicity', 'Hepatitis B/C adjunct', 'Mushroom (Amanita) poisoning (IV silibinin)', 'Liver enzyme elevation'],
    contraindications: ['Oestrogen-sensitive conditions (phytooestrogenic)', 'Ragweed allergy (Asteraceae family cross-reactivity)'],
    interactions: [
      { drug: 'Statins', severity: 'moderate', description: 'Silymarin inhibits CYP3A4 and OATP1B1; may raise statin levels — especially simvastatin. Monitor.' },
      { drug: 'Metronidazole', severity: 'minor', description: 'Competition for hepatic CYP metabolism.' },
    ],
    sideEffects: ['GI upset', 'Laxative effect (high doses)', 'Allergic reactions (Asteraceae allergy)', 'Headache'],
    evidenceSources: ['Lirussi F, J Hepatol 2002; PMID 12127423', 'Abenavoli L, Phytother Res 2010; PMID 20564545', 'European Association for the Study of the Liver (EASL) NAFLD Guidelines 2016'],
    benefits: 'Standardised silymarin extract with robust Level B evidence for hepatoprotection. Mechanisms: antioxidant, anti-inflammatory, antifibrotic, and hepatocyte membrane stabilisation. Multiple RCTs and meta-analyses demonstrate ALT/AST normalisation in NAFLD. IV silibinin (most active component) is used for Amanita phalloides poisoning.',
    organSafety: {
      renal: 'Safe in renal disease. Minimal renal involvement. No dose adjustment.',
      hepatic: 'Specifically hepatoprotective. First-line integrative therapy in NAFLD and alcohol-related liver disease.',
    },
  },
  {
    id: 'po-24',
    name: 'Quercetin PO',
    route: 'PO',
    activeIngredients: [{ name: 'Quercetin dihydrate or phytosome', concentration: '500–1000 mg/day' }],
    ebmLevel: 'C',
    ebmCategory: 'Integrative/Empirical',
    indications: ['Allergic rhinitis', 'Cardiovascular protection', 'Anti-inflammatory support', 'Senolytic therapy', 'Viral respiratory infections', 'Metabolic syndrome'],
    contraindications: ['Pregnancy', 'Hormone-sensitive cancers (theoretical phytooestrogenic activity)'],
    interactions: [
      { drug: 'Warfarin', severity: 'moderate', description: 'Inhibits CYP2C9 and platelet aggregation; monitor INR.' },
      { drug: 'Cyclosporine', severity: 'major', description: 'Inhibits CYP3A4 and P-glycoprotein significantly; may double cyclosporine levels.' },
      { drug: 'Quinolone antibiotics', severity: 'moderate', description: 'Quercetin may compete with quinolone binding sites; separate by 2 h.' },
    ],
    sideEffects: ['GI upset', 'Headache', 'Kidney injury (theoretical at very high doses)', 'Drug interactions via CYP modulation'],
    evidenceSources: ['Mlcek J, Molecules 2016; PMID 27213355', 'Messina G, Nutrients 2020; PMID 32512568', 'Senolytic Clinical Trial Mayo Clinic 2019; PMID 30287936'],
    benefits: 'Ubiquitous dietary flavonoid with mast-cell stabilising (antihistamine), anti-inflammatory (LOX/COX inhibition), and emerging senolytic properties. Mayo Clinic pilot RCT: quercetin + dasatinib reduced senescent cell burden and improved physical function in IPF. Zinc ionophore activity relevant to viral defence. Phase-2 trials ongoing.',
    organSafety: {
      renal: 'Safe at standard doses. Very high IV doses (experimental) have been associated with renal tubular injury. Oral doses safe.',
      hepatic: 'Hepatosafe at therapeutic doses. Hepatoprotective mechanisms in animal models.',
    },
  },
  {
    id: 'po-25',
    name: 'Vitamin K2 MK-7 PO',
    route: 'PO',
    activeIngredients: [{ name: 'Menaquinone-7 (MK-7)', concentration: '90–200 mcg/day' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Osteoporosis prevention', 'Arterial calcification prevention', 'Post-menopausal bone loss', 'Cardiovascular calcification', 'Vitamin D co-supplementation (calcium trafficking)'],
    contraindications: ['Warfarin therapy (major interaction)', 'Hypercalcemia', 'Sarcoidosis'],
    interactions: [
      { drug: 'Warfarin', severity: 'major', description: 'Vitamin K2 directly antagonises warfarin\'s mechanism of action. Even low doses (90 mcg) significantly reduce INR. Avoid unless under specialist supervision with very frequent INR monitoring.' },
      { drug: 'Cholestyramine', severity: 'moderate', description: 'Bile acid sequestrants reduce K2 absorption (fat-soluble); take separately.' },
    ],
    sideEffects: ['Generally very well tolerated', 'GI upset (rare)', 'Warfarin INR destabilisation'],
    evidenceSources: ['Knapen MH, Osteoporos Int 2013; PMID 23525897', 'Schurgers LJ, Blood 2007; PMID 17158229', 'Rotterdam Study (Geleijnse JM) JNCI 2004; PMID 15514115'],
    benefits: 'MK-7 is the most bioavailable dietary K2 form (fermented natto). Activates osteocalcin (directs calcium into bone) and matrix Gla-protein (prevents arterial calcification). Rotterdam Study: highest K2 intake associated with 57% lower cardiovascular mortality. Knapen RCT: 180 mcg MK-7 daily improved carotid artery compliance and reduced vertebral fracture risk.',
    organSafety: {
      renal: 'Safe in renal disease. Calcification prevention potentially beneficial in CKD-mineral bone disorder.',
      hepatic: 'Fat-soluble; hepatically processed. Safe in mild-moderate hepatic disease.',
    },
  },
  {
    id: 'po-26',
    name: 'Iodine PO (Potassium Iodide)',
    route: 'PO',
    activeIngredients: [{ name: 'Potassium Iodide', concentration: '150–300 mcg/day (RDA) | 3–50 mg/day (Lugol\'s protocol)' }],
    ebmLevel: 'A',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Iodine deficiency', 'Hypothyroidism (nutritional)', 'Thyroid nodules (euthyroid, empirical)', 'Breast fibrocystic disease', 'Radiation protection (KI)'],
    contraindications: ['Hyperthyroidism', 'Thyroid nodular disease (iodine-avid)', 'Hashimoto\'s thyroiditis (may worsen)', 'Dermatitis herpetiformis'],
    interactions: [
      { drug: 'Levothyroxine', severity: 'moderate', description: 'Excess iodine may interfere with thyroid hormone synthesis paradoxically (Wolff-Chaikoff effect); monitor TFTs.' },
      { drug: 'Anti-thyroid drugs (Carbimazole/PTU)', severity: 'major', description: 'Iodine loading pre-surgery is used deliberately; non-surgical context requires endocrinology guidance.' },
      { drug: 'ACE inhibitors', severity: 'minor', description: 'Potassium iodide + K-sparing ACE inhibitors may cause hyperkalemia.' },
    ],
    sideEffects: ['Metallic taste', 'GI upset', 'Iodism (excess: rash, runny nose, headache)', 'Thyroid dysfunction (hyper or hypo)', 'Sialadenitis'],
    evidenceSources: ['WHO/UNICEF Iodine Deficiency Report 2021', 'Zimmermann MB, Lancet 2008; PMID 19041482', 'Venturi S, Curr Chem Biol 2011'],
    benefits: 'Essential trace element for thyroid hormone synthesis (T3, T4) and breast tissue maintenance. Iodine deficiency is the most prevalent cause of preventable cognitive impairment globally. Level A evidence for correction of nutritional deficiency. Iodine at physiologic doses supports thyroid function; at pharmacologic doses (Lugol\'s) used in radiation emergency and pre-surgical thyroid preparation.',
    organSafety: {
      renal: 'Potassium component may accumulate in eGFR < 30; monitor potassium. Iodine itself is renally cleared.',
      hepatic: 'Hepatosafe. No hepatic dose adjustment required.',
    },
  },
  {
    id: 'po-27',
    name: 'SAMe PO (S-Adenosylmethionine)',
    route: 'PO',
    activeIngredients: [{ name: 'S-Adenosyl-L-Methionine', concentration: '400–1600 mg/day' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Depression', 'Osteoarthritis', 'Fibromyalgia', 'Cholestatic liver disease', 'Alcoholic liver disease', 'Intrahepatic cholestasis of pregnancy'],
    contraindications: ['Bipolar disorder (may precipitate mania)', 'Parkinson\'s disease on Levodopa without caution'],
    interactions: [
      { drug: 'SSRIs/SNRIs/MAOIs', severity: 'major', description: 'Risk of serotonin syndrome — SAMe increases monoamine activity. Do not combine with MAOIs. Use caution with SSRIs — monitor closely.' },
      { drug: 'Levodopa', severity: 'moderate', description: 'SAMe may reduce levodopa effectiveness in some Parkinson\'s patients; methylation of dopamine.' },
      { drug: 'Clomipramine', severity: 'major', description: 'Combined serotonergic effect may trigger serotonin syndrome.' },
    ],
    sideEffects: ['Nausea', 'Diarrhoea', 'Anxiety/agitation', 'Insomnia', 'Mania (bipolar patients)', 'Flatulence'],
    evidenceSources: ['Mischoulon D, Am J Clin Nutr 2012; PMID 22513989', 'Najm WI, Am Fam Physician 2004; PMID 14756625', 'Cochrane Depression Meta-Analysis 2020'],
    benefits: 'Universal methyl donor in >100 biochemical methylation reactions. Level B evidence for mild-moderate depression (comparable to tricyclic antidepressants). OA evidence: comparable to NSAID pain relief at 1200 mg/day. Hepatologically: corrects methionine cycle defects, reduces biliary obstruction in cholestatic conditions. Combines well with methylcobalamin/folate.',
    organSafety: {
      renal: 'Safe in CKD. Water-soluble; renally cleared.',
      hepatic: 'Hepatoprotective — specifically indicated in cholestatic liver disease, alcoholic liver disease, and intrahepatic cholestasis of pregnancy.',
    },
  },
  {
    id: 'po-28',
    name: '5-HTP PO (5-Hydroxytryptophan)',
    route: 'PO',
    activeIngredients: [{ name: '5-Hydroxytryptophan (Griffonia simplicifolia extract)', concentration: '50–300 mg/day' }],
    ebmLevel: 'C',
    ebmCategory: 'Integrative/Empirical',
    indications: ['Depression adjunct', 'Anxiety', 'Insomnia', 'Migraine prophylaxis', 'Fibromyalgia', 'Binge eating adjunct', 'Carbohydrate craving'],
    contraindications: ['Carcinoid tumours (5-HTP is serotonin precursor)', 'Mastocytosis', 'Tryptophan-free diet requirements'],
    interactions: [
      { drug: 'SSRIs/SNRIs', severity: 'major', description: 'High risk of serotonin syndrome; do not combine without specialist oversight.' },
      { drug: 'MAOIs', severity: 'major', description: 'Absolute contraindication — severe serotonin syndrome risk.' },
      { drug: 'Tramadol', severity: 'major', description: 'Additive serotonergic effect; serotonin toxicity risk.' },
      { drug: 'Triptans', severity: 'moderate', description: 'Both act on serotonin system; additive serotonergic effect. Use cautiously.' },
    ],
    sideEffects: ['Nausea', 'Vomiting', 'Diarrhoea', 'Drowsiness', 'Serotonin syndrome (interaction)', 'Eosinophilia-Myalgia Syndrome (if contaminated)'],
    evidenceSources: ['Shaw K, Cochrane Database 2002; PMID 12034874', 'Birdsall TC, Altern Med Rev 1998; PMID 9762747', 'Integrative Psychiatry Monograph 2022'],
    benefits: 'Direct serotonin precursor bypassing rate-limiting tryptophan hydroxylase step. Crosses blood-brain barrier freely unlike tryptophan. Three small RCTs show antidepressant effect comparable to fluvoxamine. Migraine: reduces attack frequency (5 RCTs). Fibromyalgia: reduces pain, morning stiffness, and fatigue. Combine with B6 (P5P) for optimal conversion.',
    organSafety: {
      renal: 'Safe in renal disease at standard doses. Renally excreted.',
      hepatic: 'Hepatically converted. Safe in mild liver disease. Use cautiously in severe hepatic impairment.',
    },
  },
  {
    id: 'po-29',
    name: 'Boswellia Extract PO (AKBA)',
    route: 'PO',
    activeIngredients: [{ name: 'Boswellia serrata extract (30–40% AKBA)', concentration: '300–500 mg 3x/day' }],
    ebmLevel: 'B',
    ebmCategory: 'Guidelines/RCTs',
    indications: ['Osteoarthritis', 'Rheumatoid arthritis', 'Inflammatory bowel disease (Crohn\'s)', 'Asthma', 'Brain oedema (radiation-induced)', 'Chronic inflammation'],
    contraindications: ['Pregnancy (uterotonic potential)', 'Boswellia hypersensitivity', 'Pre-operative (anti-inflammatory effect may mask pain)'],
    interactions: [
      { drug: 'NSAIDs', severity: 'minor', description: 'Complementary anti-inflammatory mechanisms; may allow NSAID dose reduction.' },
      { drug: 'Anticoagulants', severity: 'minor', description: 'Mild antiplatelet activity; caution with concurrent anticoagulant use.' },
      { drug: 'Tacrolimus', severity: 'moderate', description: 'May inhibit CYP3A4; could raise tacrolimus levels.' },
    ],
    sideEffects: ['GI upset', 'Diarrhoea', 'Rash', 'Nausea'],
    evidenceSources: ['Kimmatkar N, Phytomedicine 2003; PMID 12622457', 'Gupta I, Eur J Med Res 2001; PMID 11215498', 'German Commission E Monograph — Boswellia 2023'],
    benefits: 'Acetyl-11-keto-β-boswellic acid (AKBA) is the most potent 5-LOX inhibitor in plant medicine, blocking leukotriene biosynthesis without COX inhibition. OA RCT (Kimmatkar): 333 mg 3x/day significantly reduced pain and improved knee function. Crohn\'s disease RCT: equivalent to mesalazine for remission maintenance. Evidence-based anti-inflammatory with excellent GI tolerability.',
    organSafety: {
      renal: 'Safe in renal disease (unlike NSAIDs — no prostaglandin-mediated renal effects).',
      hepatic: 'Generally safe. No significant hepatotoxicity. Well tolerated long-term in clinical trials.',
    },
  },
  {
    id: 'po-30',
    name: 'GABA PO (Gamma-Aminobutyric Acid)',
    route: 'PO',
    activeIngredients: [{ name: 'GABA (Pharma GABA / natural)', concentration: '100–500 mg/day' }],
    ebmLevel: 'C',
    ebmCategory: 'Integrative/Empirical',
    indications: ['Anxiety', 'Insomnia', 'Stress reduction', 'Hypertension adjunct', 'PMS/PMDD adjunct'],
    contraindications: ['Severe psychiatric disorders without professional oversight', 'Pregnancy (insufficient safety data)'],
    interactions: [
      { drug: 'Benzodiazepines', severity: 'moderate', description: 'Additive GABAergic CNS depression; risk of excessive sedation.' },
      { drug: 'Antihypertensives', severity: 'minor', description: 'GABA has modest blood pressure-lowering effect; additive with antihypertensives.' },
      { drug: 'Antiepileptic drugs', severity: 'moderate', description: 'Additive GABAergic effect; monitor for excessive sedation or altered seizure threshold.' },
    ],
    sideEffects: ['Drowsiness', 'GI upset', 'Tingling/paraesthesia (transient)', 'Headache'],
    evidenceSources: ['Abdou AM, Biofactors 2006; PMID 16971751', 'Byun JI, Clin Neuropharmacol 2014; PMID 25025658', 'Japanese Functional Food Research 2022 (PharmaGABA)'],
    benefits: 'Primary inhibitory neurotransmitter in the CNS. Oral GABA bioavailability and BBB penetration is debated; PharmaGABA (naturally fermented) may act through enteric nervous system and vagal signalling to increase central GABAergic tone. Small RCTs show anxiety reduction (Byun 2014) and alpha-wave promotion on EEG (Abdou 2006). Modest evidence base.',
    organSafety: {
      renal: 'Safe in standard doses. Renally excreted.',
      hepatic: 'Hepatosafe. No hepatic dose adjustment required.',
    },
  },
];

export const preparationsById = new Map(preparations.map(p => [p.id, p]));

export const COMMON_DISEASES = [
  'Type 2 Diabetes', 'Hypertension', 'Chronic Fatigue Syndrome', "Hashimoto's Thyroiditis",
  'Hyperthyroidism', 'Hypothyroidism', 'Non-Alcoholic Fatty Liver Disease (NAFLD)',
  'Osteoarthritis', 'Rheumatoid Arthritis', 'Fibromyalgia', 'Osteoporosis',
  'Dyslipidaemia / Hypercholesterolaemia', 'Metabolic Syndrome', 'Obesity',
  'Irritable Bowel Syndrome (IBS)', "Crohn's Disease", 'Ulcerative Colitis',
  'Anaemia (Iron Deficiency)', 'B12 Deficiency Anaemia', 'COPD', 'Asthma',
  'Coronary Artery Disease', 'Heart Failure (NYHA II–III)', 'Peripheral Arterial Disease',
  'Chronic Kidney Disease', 'Polycystic Ovary Syndrome (PCOS)', 'Depression',
  'Anxiety Disorder', 'Migraine', 'Parkinson\'s Disease', 'Alzheimer\'s / Mild Cognitive Impairment',
  'Peripheral Neuropathy (Diabetic)', 'Cancer (in remission, adjunct support)',
];

export const COMMON_SYMPTOMS = [
  'Fatigue', 'Brain Fog', 'Insomnia', 'Muscle Cramps', 'Joint Pain',
  'Neuropathy / Tingling', 'Memory Problems', 'Mood Changes / Low Mood',
  'Anxiety / Restlessness', 'Headache / Migraine', 'Weight Gain',
  'Hair Loss', 'Dry Skin', 'Cold Intolerance', 'Heat Intolerance',
  'Bloating / GI discomfort', 'Constipation', 'Diarrhoea', 'Nausea',
  'Oedema / Fluid Retention', 'Shortness of Breath', 'Chest Discomfort',
  'Low Libido', 'Muscle Weakness', 'Poor Wound Healing', 'Frequent Infections',
];

export const COMMON_MEDICATIONS = [
  'Warfarin', 'Metformin', 'Levothyroxine', 'Atorvastatin', 'Rosuvastatin',
  'Simvastatin', 'Omeprazole', 'Pantoprazole', 'Ramipril', 'Lisinopril',
  'Amlodipine', 'Bisoprolol', 'Carvedilol', 'Furosemide', 'Spironolactone',
  'Aspirin', 'Clopidogrel', 'Insulin (basal)', 'Insulin (bolus)',
  'Dapagliflozin (SGLT-2)', 'Sitagliptin (DPP-4)', 'Liraglutide (GLP-1)',
  'Prednisolone', 'Azathioprine', 'Methotrexate', 'Hydroxychloroquine',
  'Levodopa/Carbidopa', 'Donepezil', 'Sertraline (SSRI)', 'Venlafaxine (SNRI)',
  'Fluoxetine', 'Escitalopram', 'Amitriptyline', 'Gabapentin', 'Pregabalin',
  'Valproate', 'Phenytoin', 'Carbamazepine', 'Cyclosporine', 'Tacrolimus',
  'Olaparib (PARP inhibitor)', 'Cisplatin', 'Doxorubicin', 'Cyclophosphamide',
];

export const COMMON_SUPPLEMENTS = [
  'Vitamin D3 (OTC)', 'Fish Oil / Omega-3', 'Magnesium (various)', 'Vitamin C',
  'Zinc', 'Multivitamin', 'Probiotics', 'Biotin', 'Iron (ferrous sulphate)',
  'Calcium + Vitamin D', 'B-Complex', 'Ashwagandha', 'Turmeric/Curcumin',
  'CoQ10', 'Melatonin', 'Vitamin B12', 'Folate/Folic Acid',
];

export const SAMPLE_PATIENT = {
  age: 55,
  gender: 'female' as const,
  weight: 82,
  height: 165,
  bmi: 30.1,
  diseases: ['Type 2 Diabetes', 'Hypertension', 'Non-Alcoholic Fatty Liver Disease (NAFLD)', 'Dyslipidaemia / Hypercholesterolaemia'],
  symptoms: ['Fatigue', 'Brain Fog', 'Neuropathy / Tingling', 'Joint Pain', 'Insomnia'],
  medications: ['Metformin', 'Atorvastatin', 'Ramipril', 'Omeprazole'],
  supplements: ['Vitamin D3 (OTC)', 'Calcium + Vitamin D'],
  lifestyle: {
    smoking: false,
    alcohol: 'moderate' as const,
    coffeePerDay: 2,
    sleepHours: 5.5,
  },
  familyHistory: ['Type 2 Diabetes', 'Coronary Artery Disease', 'Colon Cancer'],
  physicianIdeaId: 'iv-03',
};
